### ISSUE TITLE
Logo question

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardAssistant#104]
Shouldn't the new assistant also use the new Adguard logo?

![48_green](https://user-images.githubusercontent.com/10995998/28668239-34bf2516-72cf-11e7-9638-c80ca22c3557.png)

**Comment by ameshkov** [comment]
@danidoedel there are actually two forms of the new logo: green with a white check mark and green border and a green check mark (looks like the old logo indeed).

**Comment by danidoedel** [comment]
Hmm that‘s a bit confusing to be honest and I don‘t see the benefit of having two different logos, but that‘s just my opinion ;)
