### ISSUE TITLE
A problem with blocking ads 

### ISSUE THREAD

**Issue by thislife81** [AdguardTeam/AdguardAssistant#105]
Site: http://turbo.az/
Screen: http://s3.postimg.org/uk3kcreib/screenshot_8.png (I can't block these black sections)

**Comment by ameshkov** [comment]
You actually can, select them, move the slider left a bit and check "Block similar elements":
https://monosnap.com/file/jiK7MjJvejO3MWFJYmu9LOtnhVrOSQ
