### ISSUE TITLE
Adguard Assistant icon size setting reset bug

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#110]
@DandyClubs commented on [Tue Aug 08 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/1881)

Steps to reproduce:

1. Open any page and change Adguard Assistant's size and position.
2. Open any other page, i.e. http://cafe.naver.com/blueberrystudy
3. Adguard Assistant's size an position remains the same

### Your environment
adguard for windows 6.2.390.2018
edge 38.14393.1066.0
windows 10 64bit 1703

---

@vozersky commented on [Tue Aug 08 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/1881#issuecomment-320975113)

can't reproduce

@DandyClubs  do you still have this issue? 

---

@DandyClubs commented on [Tue Aug 08 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/1881#issuecomment-321028597)

https://drive.google.com/file/d/0B0t052iXG1Qtc041dFlDY2haTXM/view

how to change default icon size from large to small? 

---

@vozersky commented on [Wed Aug 09 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/1881#issuecomment-321235152)

@DandyClubs oh, so it happens in Edge browser, not Chrome, thanks a lot for reporting the problem! Moving the issue to Assistant repository.

**Comment by DandyClubs** [comment]
it happens in firefox, chrome, edge, IE

i test adguard 6.1, 6.2

**Comment by 4-life** [comment]
Edge always return `undefined` in GM_getValue('settings') only on this site  http://cafe.naver.com/. So the default settings are applied

**Comment by ameshkov** [comment]
@4-life debug it deeper, why does it return undefined?

**Comment by seanl-adg** [comment]
I noticed that this page overwrites `Function.prototype.bind` to a method which is not compliant to the specification. This was causing some problem in the userscript wrapper's side, and this may affect the userscript content code too.

This website does not overwrite `Function.prototype.apply` or `Function.prototype.call`, so this issue can be workarounded by using a custom `bind` polyfill using them.

**Comment by ameshkov** [comment]
Can't we protect it for our wrapper?

**Comment by seanl-adg** [comment]
It is theoretically possible, but it will add another overhead during the userscript wrapper startup phase. Tampermonkey doesn't provide this kind of protection either,

**Comment by ameshkov** [comment]
Can we make an exception just for a couple of really important functions?

`Promise`, `bind`, `XMLHttpRequest` -- these are often overriden by the pages.

**Comment by ameshkov** [comment]
@4-life we should use `bind` polyfill to make it work

**Comment by ameshkov** [comment]
@seanl-adg it appears that the issue is on the wrapper side after all.

Here's what TS compiler generates:
`var GM_setValue = __GM_api.GM_setValue.bind(__GM_api);`

**Comment by 4-life** [comment]
In the new build it fixed

**Comment by ameshkov** [comment]
.419
