### ISSUE TITLE
ulmart.ru - Assistant issue

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#111]
@vbagirov commented on [Tue Jan 31 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/1530)

Jn the ulmart.ru website Assistant icon is present, but once you click on it the Assistant window appears somewhere above. All the attempts to move the window fail.

Original thread: 
https://forum.adguard.com/index.php?threads/20/page-7#post-124788

**Comment by 4-life** [comment]
Fixed by #129
