### ISSUE TITLE
Assistant is not shown on a website

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#112]
@vbagirov commented on [Tue Apr 05 2016](https://github.com/AdguardTeam/AdguardForWindows/issues/1016)

http://freefootball.in/hd/ss2.php

Originally from http://forum.adguard.com/showthread.php?10376

---

@vozersky commented on [Mon Aug 14 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/1016#issuecomment-322136136)

obsolete

**Comment by vozersky** [comment]
please check

**Comment by 4-life** [comment]
They are setting style `visibility: hidden` for body
