### ISSUE TITLE
price.ru - Assistant disappears when you click on it

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#113]
@vgavrish commented on [Mon Jan 09 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/1483)

1018240
When you click on Assistant, it hides with menu.
Chrome, Opera
6.1.298.1564

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21759399/ab233a46-d64c-11e6-8041-ff8017675384.png)

![image](https://cloud.githubusercontent.com/assets/18548949/21759407/b4fad77c-d64c-11e6-8f12-f79aad767c5f.png)

**Comment by 4-life** [comment]
They are overrides styles `iframe {height: 0}`
