### ISSUE TITLE
http://topcomputer.ru/catalog/413/ - assistant is not working

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#114]
@vgavrish commented on [Sun Dec 11 2016](https://github.com/AdguardTeam/AdguardForWindows/issues/1444)

1062718
На главной topcomputer.ru Помощник отображается, но не на других страницах сайта
Chrome, Opera
http://prntscr.com/dhzoc1

**Comment by 4-life** [comment]
У них каждые 200мс удаляются новые дивы и айфреймы:
`interval = setInterval(function(){
	testCount++;
	if(!lastDiv) lastDiv = $('div#last');			
	if(!$(lastDiv).length)
	{
		//console.log('end');
		clearInterval(interval);
		return;
	}

	if(!!$('html').attr('style')) $('html').attr('style', '');			
	//$('head style').each(function(){if($(this).text().indexOf('sovetnik') != -1)$(this).remove();});

	$(lastDiv).nextAll('div,iframe').each(function(){				
		var el = this;
		var del = true;
		var tag = $(el).get(0).tagName.toLowerCase();				
		switch(tag)
		{
			case 'div':						
				var id = $(el).attr('id');
				var clss = !!$(el).attr('class') ? $(el).attr('class') : '';						
				if(/fancybox/i.test(id) || clss == '' || /(window|ui\-dialog|bx\-|ui\-widget\-overlay|qtip)/i.test(clss))
					del = false;
				break;					

			case 'style':
				if($(this).text().indexOf('sovetnik') != -1)
					del = true;
				break;
		}

		if(del)
		{
			console.log(el);
			$(el).remove();
			dc++;
		}
	});		

	if(dc > 0 && testCount < 50) testCount+=50;

	if(testCount >= 200)
	{
		clearInterval(interval);
		//console.log('end');
		return true;
	}
} , 200);`

Можем под них индивидуальный обход сделать в этом месте `clss == '' || /(window|ui\-dialog|bx\-|ui\-widget\-overlay|qtip)/i.test(clss))`, но нужно ли?
