### ISSUE TITLE
Assistant hotkeys

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#117]
@ameshkov commented on [Thu Jan 21 2016](https://github.com/AdguardTeam/AdguardForWindows/issues/755)

http://forum.adguard.com/showthread.php?8832-AdGuard-Windows-Blocking-Element-Feature-Improvement-Request

---

@evgeniy-ADG commented on [Thu May 12 2016](https://github.com/AdguardTeam/AdguardForWindows/issues/755#issuecomment-218701088)

> I often find myself disabling AdBlocker temporarily, sometimes it's because its blocks content in addition to ads, sometimes because it might be blocking a function I wish to use - both issues which is completely normal when using an ad blocker. But it would be a lot faster if you could add an option to have user defined hotkey to switch it on and off. Hopefully this is something you can put in the suggestion box for future development.

IUT-829-46645

**Comment by dj-sorry** [comment]
https://qcrm5.supportyourapp.com/#/customer/2178456
