### ISSUE TITLE
Do not reload page after adding a new rule through AG Assistant

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#120]
@ameshkov commented on [Thu Jan 21 2016](https://github.com/AdguardTeam/AdguardForWindows/issues/756)

http://forum.adguard.com/showthread.php?8832-AdGuard-Windows-Blocking-Element-Feature-Improvement-Request

**Comment by 4-life** [comment]
fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/4c7140e027bc9c1ae81d0a21f2d9cb8758b30d23
