### ISSUE TITLE
AG Assistant does not work when cookies are disabled

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#124]
@ameshkov commented on [Fri Mar 04 2016](https://github.com/AdguardTeam/AdguardForWindows/issues/943)

http://forum.adguard.com/showthread.php?9273-Adguard-assistant-and-cookies

@suhan3z why could it be so?

**Comment by vozersky** [comment]
need to check this one

**Comment by 4-life** [comment]
In content settings for cookies we can choose the param `Block sites from setting any data` which means also localStorage! In console error msg: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

**Comment by ameshkov** [comment]
So we should handle this case
