### ISSUE TITLE
Improve Assistant performance

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#132]
Currently, it takes ~50ms to execute the Assistant script. Why so much?

**Comment by ameshkov** [comment]
Comment by @seanl-adg

> I used Chrome devtool's performance tab with AG Assistant enabled on example.com.

> It highlights 2 function calls that are taking long time.

> * getResource: As I understand, currently certain html and css resources are included in the assistant code in a base64 encoded JS string. I'm not sure what benefit does base64 encoding provides here. It seems that decoding the string is causing significant execution time (on my machine), if those will only be used in its decoded form, I think directly storing it in its decoded form would reduce the execution time. Also, we could use html/css minifiers in build time before including them.
> * getCoords: According to the screenshot, the getBoundingClientRect call is causing a rather heavy browser style recalculation. As I understand, the call used to store the coordinates of the button which will be used. I think, if we somehow defer the call to getCoords until user clicks the assistant button, we may reduce the time taken in executing the assistant's code (and so page's other script will be executed earlier). Also, getBoundingClientRect returns subpixel data too, which may not be needed for our use cases. apis like element.offsetLeft or element.scrollLeft returns integers and I suppose those are less costly. We are doing some addition and subtraction with the returned number from getBoundingClientRect and UIEvent.pageY, but UIEvent.pageY also returns an integer, so subpixel information from getBoundingClientRect may be redundant.

**Comment by 4-life** [comment]
these are the main functions on which the assistant is based. Change them is a big refactoring

**Comment by ameshkov** [comment]
1. We can get rid of `getResource` relatively easy by changing the build script.
2. What for `getBoundingClientRect`, it's unclear how complicated change would it be.

Please tell me how long will this refactoring take?

**Comment by 4-life** [comment]
get rid of ```getResource``` it's not at all easy. It worries me more than ```getBoundingClientRect```. Maybe we should getting css and html like ```// @resource     style https://AdguardTeam.github.io/AdguardAssistant/style.css```?

Changing ```getBoundingClientRect``` it's not too long by 1 day, but popular libraries like MooTools or jQuery use ```getBoundingClientRect``` as well.

**Comment by ameshkov** [comment]
`// @resource style  ` -- as I recall, under the hood is the same, works with base64 encoded string
