### ISSUE TITLE
avxhm.se -- Assistant misbehaves

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#135]
First of all, I see this warning in the console:
`Environment doesn't satisfy requirements, so don't show Adguard`

However, Assistant button is visible, it just misbehaves when you bring up the menu and try to select an element.

**Comment by 4-life** [comment]
Extended logs added in the new build: https://github.com/AdguardTeam/AdguardAssistant/commit/83026d6898dc7413259d0215c3b72b34e17f79c5
