### ISSUE TITLE
[gui] Adguard Assistant translation text is too long

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#136]
@FadeMind commented on [Wed Sep 27 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/1942)

![2017-09-27 08_01_00-new issue adguardteam_adguardforwindows opera](https://user-images.githubusercontent.com/9846948/30898150-0bec3c3a-a35a-11e7-9e72-4af784a6c89d.png)

Window is too small and text appear under icons. Solution. Shortcut text labels. Here is polish language translations.

**Comment by ameshkov** [comment]
@4-life let's add max-width to the menu items labels
