### ISSUE TITLE
The assistant iframe is rendered without style

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardAssistant#137]
I'm using Firefox 57.0b3, and on it, sometimes the assistant ui frame is rendered before styles are applied.
Attached a screencast demonstrating the issue: [1.zip](https://github.com/AdguardTeam/AdguardAssistant/files/1337703/1.zip)

**Comment by 4-life** [comment]
In this case browser engine sets how to rendering content

**Comment by ameshkov** [comment]
So styles are added immediately? No async operation in between?

**Comment by 4-life** [comment]
Not immediately but faster as it possible to execute and append styles to page

**Comment by ameshkov** [comment]
```
            doc.write(StringUtils.format("<html><head>{0}</head></html>",
                StringUtils.format('<style {0} type="text/css">{1}</style>', getStyleNonce(), resources.getResource('style.css'))));
```

**Comment by ameshkov** [comment]
so basically styles are appended BEFORE the frame content

**Comment by 4-life** [comment]
Styles are appended after the frame content because we need to wait for the frame load event to be able to write to it

**Comment by ameshkov** [comment]
@4-life shouldn't you append it to body AFTER appending the style?
https://github.com/AdguardTeam/AdguardAssistant/blob/master/src/iframe.js#L71

**Comment by 4-life** [comment]
Styles in parent page does not passing to iframe page!

**Comment by ameshkov** [comment]
I mean that maybe you should append **the iframe** to the parent window **after** the iframe was loaded
