### ISSUE TITLE
Assistans' bugs (v. 4.0.11)

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/AdguardAssistant#138]
I'm using Chrome 61.0.3163.100, AdGuard assistant 4.0.11 (not beta). 
1. When I click "Report the website" nothing happens. Also, there are no errors in the console.
2. When I set Icon size for the Assistant on one webpage, it affects to other webpages, which will be loaded after.

**Comment by ameshkov** [comment]
1. Isn't the bug is on the program side?
2. Not a bug

**Comment by confessor-adguard** [comment]
> When I click "Report the website" nothing happens. Also, there are no errors in the console.

Definitely an app bug.
A new issue in Adguard for Windows repo was created.
