### ISSUE TITLE
Cannot select an iframe on the website

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#142]
## Steps to reproduce:

1. Open http://www.ky3.com/weather/
2. Scroll down to this block: https://uploads.adguard.com/up04_5diow_KY3_Springfield_Missouri_News_Weather_and_Sports_in_the_Ozarks__KY3_-_Weather.png
3. Try to block it with Assistant

## Expected behavior
Block is replaced with an iframe placeholder, then you can select and block it

## Actual behavior
Selection disappears along with the placeholder once you click on the block

**Comment by ameshkov** [comment]
@4-life should be back-ported to the browser extension

**Comment by BooBerry** [comment]
Also happens on http://www.kspr.com/weather/
