### ISSUE TITLE
"Block ads on this website" tool is misbehaving in Firefox

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardAssistant#146]
So, it's the same as: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/671
it is reproducible on each website.

maybe finally we can find a solution. 

Basically right now you can't use the main tool of Assistant in FF browser.

**Comment by 4-life** [comment]
@zebrum check please the latest build with solution https://adguardteam.github.io/AdguardAssistant/assistant.user.js

**Comment by zebrum** [comment]
works fine
