### ISSUE TITLE
Rework Assistant menu header

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardAssistant#148]
Can we do this:
1. click on green circle redirect to WoT site statistic (e.g.  https://www.mywot.com/ru/scorecard/www.yandex.ru)
2. click on WoT logo redirects to WoT main page  (https://www.mywot.com/)
3. other area do not redirect anywhere, but you can click and drag menu's window around website page

![screenshot at oct 12 19-47-59](https://user-images.githubusercontent.com/23637588/31508300-469e20cc-af86-11e7-8c0e-58c6b8c26e79.png)

**Comment by vbagirov** [comment]
Currently wot page opens anyway when you release the click after dragging the window by the wot area.

**Comment by 4-life** [comment]
Fixed https://github.com/AdguardTeam/AdguardAssistant/commit/76b0801966511c56e9492a4a67857e10825045fb
