### ISSUE TITLE
hdrezka.ag - Adguard assistant disappears after click

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#150]
@Yulia-ADG commented on [Thu Oct 19 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/1975)

### Steps to reproduce
http://hdrezka.ag/films/thriller/25830-hranilische-2017.html
1. Open any subpage of hdrezka.ag (works normally on the main page)
2. Click on Adguard assistant 

### Expected behavior
It should open normally

### Actual behavior
It disappears. Appears again after page reload. If you click again, it disappears again too.

<details><summary>Screenshot:</summary>

</details>

### Your environment

*Adguard version 6.1.331.1732
* Chrome version 61.0.3163.100
* Windows 10

---

@ameshkov commented on [Sun Oct 22 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/1975#issuecomment-338481488)

@vozersky first of all, this one should be moved to the Assistant repo.

Most likely they use some kind of an "anti-AG" script like the one on rutor. Shouldn't be fixed if so.

**Comment by 4-life** [comment]
Can't reproduce. What assistant version is used?

**Comment by vozersky** [comment]
works fine with 6.2.433.2167 (Assistant 4.0.15)
