### ISSUE TITLE
Label "Report the website" misleading

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardAssistant#151]
As the option "Report the website" leads to AdGuard site to report missed ads and stuff the option should be renamed to something like "Report ads on this website". The current label is a bit misleading and does not reflect the actual function of the button. But that's just my opinion ;)

![image](https://user-images.githubusercontent.com/10995998/32142877-ad6916aa-bca0-11e7-8001-23e6e4c6e30f.png)

**Comment by vozersky** [comment]
I totally agree

**Comment by ameshkov** [comment]
But what if it's not ads? You can report "incorrect blocking" there as well
