### ISSUE TITLE
AdGuard Assistant is missing in the Opera browser

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardAssistant#153]
Windows OS
Opera 48.0

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/27292111/32310317-02eacc26-bf9a-11e7-8d0f-57aa9a2deb12.png)

![image](https://user-images.githubusercontent.com/27292111/32310254-b85f74ae-bf99-11e7-8784-f7c1ecd534c1.png)

![image](https://user-images.githubusercontent.com/27292111/32310256-bc03d94c-bf99-11e7-83dc-594c3277e367.png)

![image](https://user-images.githubusercontent.com/27292111/32310287-dd120438-bf99-11e7-8c08-c80e622698d8.png)

</details><br/>

Ticket ID: 1652300

**Comment by vozersky** [comment]
can't rep
