### ISSUE TITLE
Exclude common frames from Assistant and WOT scripts

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#154]
Embedded Youtube player iframe
Embedded Vimeo player iframe
Embedded Coub player iframe
Facebook communication iframe
VK communication iframe
Twitter communication iframe

**Comment by 4-life** [comment]
Maybe we should to check ```window.opener.document```, which is returned ```document``` object in frame and ```undefined``` or error exception in the main page?

**Comment by ameshkov** [comment]
The point is that I don't want AG to inject our userscripts into these frames

**Comment by 4-life** [comment]
by url?

**Comment by ameshkov** [comment]
https://tampermonkey.net/documentation.php#_exclude
