### ISSUE TITLE
Slider disappears after you select the max area and exit preview

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#155]
https://uploads.adguard.com/up05_s9f8g.mp4

**str:** 
select the max area, enter the preview mode, then exit it

**expected behavior:** 
you exit the preview mode as usual

**actual behavior:** 
you start creating\adjusting the rule instead

**Comment by 4-life** [comment]
It's normal work. Max area doesn't have parent elements, so slider is empty
