### ISSUE TITLE
Assistant is not being displayed when body is a frameset node

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardAssistant#156]
Problem url: http://blog.naver.com/lumines103/221148508282
The assistant icon is not being displayed, caused by `document.body` being a `frameset` node.
There was a similar issue with popup blocker: https://github.com/AdguardTeam/PopupBlocker/issues/64

**Comment by ameshkov** [comment]
Proposed fix from the popup blocker:
https://github.com/AdguardTeam/PopupBlocker/commit/84fe773e30710d7719e238aa8f461f297a0ae08e

**Comment by 4-life** [comment]
We can't use assistant in frameset node because assistant does't work in frameю. Or we should have as many icons as there are frames

**Comment by ameshkov** [comment]
@4-life check the link: https://github.com/AdguardTeam/PopupBlocker/commit/84fe773e30710d7719e238aa8f461f297a0ae08e

**Comment by ameshkov** [comment]
User won't be able to select anything inside of the frame, though.

**Comment by ameshkov** [comment]
But at least he'll be able to report ads via assistant

**Comment by 4-life** [comment]
https://github.com/AdguardTeam/AdguardAssistant/commit/d3e8d7071bd50b7414ed08a2cd15ad5bc058ca52
