### ISSUE TITLE
New Safari for iOS Assistant misbehaves on some websites

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#157]
example:
Assistant panel is too small at mobiletelefon.ru:

![image](https://user-images.githubusercontent.com/17472907/33995391-e4b4bbe2-e0ee-11e7-948f-84226e2f89cf.png)

**Comment by 4-life** [comment]
it's normal work. When changing the screen size, the panel just stretches

**Comment by ameshkov** [comment]
This behavior is not okay, it's plain ugly and unusable.

Please remind me of that issue later, I'll come up with updated reqs for the Assistant mobile UI.

**Comment by BlazDT** [comment]
I guess we should have it movable like on Windows as not every element can be selected as seen in referenced issue.

**Comment by 4-life** [comment]
New mobile UI released https://github.com/AdguardTeam/AdguardAssistant/releases/tag/4.0.17
