### ISSUE TITLE
cnbc.com - Assistant is still on the website 

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardAssistant#158]
https://www.cnbc.com/world/?region=world
I’ve added an exception to ‘cnbc.com’ using the Adguard
assistant and for some reason it doesn’t seem to work. The assistant
still loads with the page.

<details><summary>Screenshot:</summary>

![screen shot 2017-12-16 at 1 22 18 am](https://user-images.githubusercontent.com/27292111/34064200-fc5644d4-e1ff-11e7-9cfa-1d273cef1bc5.png)

![screen shot 2017-12-16 at 1 23 45 am](https://user-images.githubusercontent.com/27292111/34064203-ffc7efd2-e1ff-11e7-9200-3eb8ca0a66b8.png)

</details>

Ticket ID: 1692072

**Comment by ameshkov** [comment]
The problem is in another rule in the English filter.

To solve it, add the following rule to the user filter:
```
@@||cnbc.com$document,important
```
