### ISSUE TITLE
AdGuard puts userscript into textarea

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#165]
Issue details are here:
https://github.com/AdguardTeam/AdguardForWindows/issues/2050

See comment by @seanl-adg 
> An issue with eval has been fixed in the pull request, but this website additionally defines a custom document.createElement, and it is still causing an issue with the Assistant.

**Comment by 4-life** [comment]
solution: https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createHTMLDocument
