### ISSUE TITLE
No Assistant on feedly.com

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardAssistant#166]
No Assistant on feedly.com

https://github.com/AdguardTeam/AdguardFilters/issues/9704

**Comment by 4-life** [comment]
@ameshkov why we added feedly.com in exclude list? https://github.com/AdguardTeam/AdguardAssistant/blob/master/compiler.meta.template.js#L12

**Comment by ameshkov** [comment]
Assistant was causing issues with it back then.

Could you please check if this is still the case now? Check it in both Chrome and FF please.

**Comment by 4-life** [comment]
Works good in chrome, ie, edge, but in firefox assistant icon disappearing

**Comment by ameshkov** [comment]
@4-life is it still an issue? Please check.

**Comment by 4-life** [comment]
@ameshkov happens in Firefox

**Comment by ameshkov** [comment]
@4-life any idea why?

**Comment by 4-life** [comment]
@ameshkov insert styles by style tag instead gmApi.GM_addStyle fix the problem

**Comment by ameshkov** [comment]
What exactly is the problem with `GM_addStyle`?
