### ISSUE TITLE
Default appearance

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardAssistant#17]
It would be neat to be able to set a appearance that applies to all websites where the user did not customize it.

I don't want to manually set the icon size to small for every domain i visit :(

**Comment by BooBerry** [comment]
Yep, this is exactly my issue with the new Assistant. I prefer to set the default size and position to be a small icon on the bottom left. With the new Assistant, I can't set a global size and position for the Assistant - it's all per-site now. Having a "global settings" option within the Assistant to set a global size and position would be best, IMO.

Until then, I have to disable the Assistant as I can't actually stand having the large Assistant icon on the bottom right by default.

**Comment by vozersky** [comment]
@Bluscream @BooBerry have you restarted the browser after update?

**Comment by BooBerry** [comment]
Yep, of course. Even cleared browser caches, rebooted the PC, etc. There isn't a way to set a global default (in regards to Assistant size and location for all websites, in addition to the new per-website settings) for the new Assistant.

**Comment by vozersky** [comment]
@BooBerry what version of chrome do you use?  any errors in browser console?

**Comment by vozersky** [comment]
Also, have you tried any other browsers?

**Comment by Bluscream** [comment]
@vozersky why do you think we experience a bug?

**Comment by BooBerry** [comment]
It happens in all web browsers (Chrome, Firefox, Chrome Canary, Firefox Nightly and Edge).

Haven't checked the console for errors (I'm not at the PC right now to check) but it looks like to me there's no way in the new Assistant to set a global, default for all websites.

I don't think it's a bug, but an oversight in the new Assistant.

**Comment by Bluscream** [comment]
I think he just doesn't get what we mean, lets wait for ameshkov then :>

**Comment by vozersky** [comment]
Because, obviously, you two are the only people able to reproduce this problem so far

**Comment by Bluscream** [comment]
There is no problem, its just a missing setting/feature

**Comment by BooBerry** [comment]
Actually, there is an error in the Chrome's console on every website, which is for the Assistant;

`SyntaxError: Unexpected token u in JSON at position 0`

Using the latest Chrome stable build, 58.0.3029.81 64-bit on Windows 10.

**Comment by BooBerry** [comment]
Yep, figured it out. It happens only in Chrome - if you set it in Firefox, it'll work fine globally for all others browsers.

But for whatever reason, you can't set it in Chrome. I'll test other browsers and see if any others are broken this way.

**Comment by vozersky** [comment]
@BooBerry could you please uncheck "Use beta channel for updates" in Adguard general settings, restart the Chrome and see if it helps?

**Comment by Bluscream** [comment]
@BooBerry so it's intended to be global. And global only? (Not per site?)

**Comment by BooBerry** [comment]
After setting it in Firefox, it does work correctly in Chrome now. Very strange, it's like you can't set it for the first time in Chrome which throws the above error off in the console, but if you set it in another browser then re-open Chrome it'll work fine then.

And yes, it seems to be global. Just don't use Chrome (and likely Opera, Vivaldi, etc.) to change the Assistant's size and location defaults!

**Comment by Bluscream** [comment]
Ah okay, im using FF fev branch btw. I must have overseen the fact that its global only when i was reading the changelog

**Comment by Bluscream** [comment]
Haveing per-site config makes sense tho, atleast for the positioning

**Comment by BooBerry** [comment]
The Assistant size/location settings seem to be global. But from there, there can be a per-site config by dragging the Assistant around anywhere on the site and it should remember the location.

I'm about to see if I can reproduce this by upgrading to the latest beta in my Windows 10 virtual machine, and see if the error pops up again in Chrome 58's console.

**Comment by BooBerry** [comment]
Yep, it gives off an error in Chrome's console after updating to the latest 6.2 beta.

```
Invalid settings object
print @ Adguard Assistant Beta?ts=0:107
```

**Comment by Bluscream** [comment]
You might want to reate a new issue tho, my initial feature request was explained and as such resolved.

**Comment by vozersky** [comment]
@BooBerry 

Yep, that's correct, "Assistant settings" are global, and the manually set icon location is per site. 

@Bluscream @BooBerry 

This is actually a serious bug. I can reproduce it now, thanks a lot for reporting it, guys!

**Comment by BooBerry** [comment]
Glad to be a help (as always!). :)
