### ISSUE TITLE
Make a pause in one string on oneskyapp.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardAssistant#170]
@aalpatkina 

Original:
Move the slider to change the size of the frame the new rule will work for:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/aylTZm1.png)
</details><br/>

Modified:
Move the slider to change the size of the frame. The new rule will work for:

**Comment by aalpatkina** [comment]
@lancelot-moon the original phrase "Move the slider to change the size of the frame the new rule will work for:" is correct

**Comment by lancelot-moon** [comment]
Between the frame and the new rule, there is no conjunction.
Or they should be 2 sentences.
The grammar in that string is strange.

**Comment by vbagirov** [comment]
@lancelot-moon they really should not. As @aalpatkina said, the sentence is grammatically correct, if somewhat complicated. You can mentally divide it into parts:

`Move the slider to change the size of the || frame the new rule will work for:`

Here the `the new rule will work for` part is a descriptive for `frame`, like in "a frame that will be affected by the newly created rule". Maybe we can just change the phrase to this variant, we'll think about it. Thank you for your constant vigilance :)
