### ISSUE TITLE
Assistant hangs up yahoo.com page on iOS 11 in Safari

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardAssistant#171]
1. open yahoo.com in Safari
2. Run Assistant and try to block smthg

Expected result: Assistant works correctly, user able to choose element to block, etc

Actual result: browser don't answer, page is frozen

AdGuard Pro for ios 2.0.0(126) Assistant 4.0.17
 Reproducible on iOS 11

on iOS 10 works as expected.

**Comment by 4-life** [comment]
Same issue on all browsers and platforms

**Comment by ameshkov** [comment]
@4-life so? Have you fixed it?

**Comment by 4-life** [comment]
Fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/24465bfdb79d5ca98620c2d10a4c81a22f993153
