### ISSUE TITLE
Assistant does not show up in Maxthon Cloud Browser 4.4.8.2000

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardAssistant#172]
The browser is added to the list of filtered apps, you can see it's really being filtered in the log, but I couldn't make the Assistant appear. The built-in ad blocking has been turned off.

### Steps to reproduce

1. Install Maxthon
2. Make sure it's added to the list of filtered apps
3. Open Maxthon, go to any website
4. There's no Assistant

### Your environment

* AdGuard extension version: the latest available
* Environment name and version: Maxthon Cloud Browser 4.4.8.2000
* Filters you use in AdGuard: n/a
* Any other browser extensions you have installed: none

**Comment by vozersky** [comment]
confirmed

![image](https://user-images.githubusercontent.com/17472907/35350374-c949bb48-014e-11e8-8442-62f7ded66031.png)

**Comment by ameshkov** [comment]
Moved to https://github.com/AdguardTeam/AdguardForWindows/issues/2093
