### ISSUE TITLE
Assistant icon doesn't appear on "level.com.tr"

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardAssistant#173]
The assistant is missing on this website, on other websites, Asisstant works well!
website: https://www.level.com.tr/makale/world-of-warplanes-2-0-ile-tanisin.html
AdGuard for Windows : 6.2.437.2171
Browsers : Firefox Nightly & Opera Dev
Screenshot
![missed_icon](https://user-images.githubusercontent.com/15933805/35459347-cea51fda-02f0-11e8-9432-2d992bda6957.png)

**Comment by 4-life** [comment]
It works fine from tampermonkey but didn't load from application.

**Comment by bkrucarci** [comment]
@4-life 
Yes, it seems fixed. You can close the topic.
Thanks
