### ISSUE TITLE
Adguard Assistant breaks Google Docs

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardAssistant#18]
Reproduced on
https://docs.google.com/spreadsheets/u/0/
FF, Chrome
<details>

![image](http://imagizer.imageshack.com/img922/681/8jjj95.png)
</details>
https://forum.adguard.com/index.php?threads/21253/

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardAssistant/issues/24

**Comment by confessor-adguard** [comment]
Will be resolved in #24.

**Comment by williamli** [comment]
It is still killing Google Docs on Safari (not Chrome)
![screen shot 2018-05-16 at 17 44 52](https://user-images.githubusercontent.com/179761/40109899-23aea2d0-5931-11e8-874f-e505d3684542.png)

**Comment by ameshkov** [comment]
@4-life I suggest excluding `docs.google.com` domain from both old and new versions of Assistant.

**Comment by williamli** [comment]
Seems like it's the problem of the French filter.


I think I should've reported the bugs over at the Adguard Mac area...
Ref: https://github.com/AdguardTeam/AdguardForMac/issues/312#issuecomment-389463814

**Comment by ameshkov** [comment]
@Alex-302 please take a look

**Comment by ameshkov** [comment]
@williamli does it happen with any document or just with some specific one? Spreadsheet or doc or smth else?
