### ISSUE TITLE
Filtering status switch twitches upon Assistant window opening

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardAssistant#181]
If filtering on the website is enabled, it will be shown as disabled for a fraction of a second, then switch to "enabled".

**Comment by ameshkov** [comment]
@4-life I thought we've already resolved it once?

**Comment by 4-life** [comment]
It's happens in a first open. Next time it's not occur. Does we need to fix it?

**Comment by ameshkov** [comment]
Define "first time" plz. First time after page is loaded or first time for a particular website

**Comment by 4-life** [comment]
@ameshkov first time for a particular website

**Comment by ameshkov** [comment]
It's okay then
