### ISSUE TITLE
Make the "small" icon smaller

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardAssistant#182]
Many users still find the current "small" icon too big. Consider renaming "small" icon to "medium" and adding an even smaller one (reference -- "small" icon from the previous Assistant version).

**Comment by ameshkov** [comment]
Here's the size I suggest:
https://uploads.adguard.com/up04_4qrn7_Lenta.ru.png

**Comment by zebrum** [comment]
It looks like new icon size is the same as previous.

**Comment by zebrum** [comment]
ok, I get it :)

**Comment by BooBerry** [comment]
Yeah, it'll still appear big if the Assistant is cached in the browser cache. Clearing the browser cache fixes it and it looks nice and small again (though blank in Edge/Firefox, which is a different issue).
