### ISSUE TITLE
Assistant Menu Appeared Behind the Content

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardAssistant#185]
Please watch: http://recordit.co/WRsF1erFms
Website: http://www.milliyet.com.tr/
AdGuard for Windows: v6.2.437.2171
Assistant version: beta 4.1.2

**Comment by ameshkov** [comment]
@4-life happens in Firefox

**Comment by bkrucarci** [comment]
@ameshkov @4-life 
Updated to 4.1.4
The problem is still exist, it is not solved. Please check again.

**Comment by vbagirov** [comment]
@bkrucarci I tried it too with v4.1.4 and experienced no such bug. Try flushing the cache maybe?

**Comment by bkrucarci** [comment]
I checked today and it seems working normally.
@vbagirov I use built-in updater system on AdGuard for Windows.
I tried to link that you gave on your message, it says "Dev" build with v4.1.4.
But I have v4.1.4 "Beta" release. Same version number but 2 different release.

**Comment by vbagirov** [comment]
@bkrucarci the Beta version of  Assistant you have looks into cdn.adguard.com for updates, and there it is  indeed labeled as 'Beta', the one on GitHub is labeled as Dev, but essentially they are the same two extensions in this case.

Since the problem seems to be resolved, I will close the issue.
