### ISSUE TITLE
Blank Assistant icon

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardAssistant#186]
https://uploads.adguard.com/up03_kj859.mp4

1. Blank icon
2. Assistant menu behind layers.

Assistant 4.1.3
Firefox 58.0.2, Microsoft Edge 38.14393.0.0

**Comment by BooBerry** [comment]
Yep, seeing it here in Edge and Firefox.

**Comment by ameshkov** [comment]
Resolved in the new update
