### ISSUE TITLE
Assistant icon reverts to large size when it's disabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#188]
This one should be tested with AdGuard for Windows.

Original report:
https://forum.adguard.com/index.php?threads/adguard-no-longer-working-on-youtube.27954/#post-164585

Steps to reproduce:

1. Change Assistant icon size to small
2. Disable protection via Assistant menu

Expected result:
Protection is disabled, Assistant icon remains small

Actual result:
Assistant icon reverted to large

**Comment by 4-life** [comment]
Can't reproduce

**Comment by ameshkov** [comment]
Have you tested it with AG v6.2?

One more thing, it seems that the issue happens on Youtube specifically. Could you please try to reproduce it one more time, try navigating there, opening different videos.

**Comment by 4-life** [comment]
Yes v6.2. On YouTube this is not happening. After disabling the protection through the Assistant menu, the page reloaded and there is no more action, just like reload the page by user, the icon will be correct. This issue possible only if a browser doesnt support localstorage, but in this case other settings also will be reset after reload page

**Comment by vbagirov** [comment]
The issue seems to be unrelated to Assistant. I have cleared the milestone for now, it should not prevent us from releasing Assistant v4.1.
