### ISSUE TITLE
Assistant settings reset

### ISSUE THREAD

**Issue by Bushido1** [AdguardTeam/AdguardAssistant#19]
After updating to the latest Beta version, I noticed that I have to configure Assistant settings again. If I just update, not install for the first time, should the Assistant settings stay as they are? It is annoying to make Assistant icon smaller again from settings after every Adguard for Windows update.

**Comment by Bushido1** [comment]
Now I have not even updated Adguard for Windows and suddenly after starting web-browser, I see that Assistant icon is again in ,,Large" mode.

**Comment by ameshkov** [comment]
Filed an issue in the windows repo about it:
https://github.com/AdguardTeam/AdguardForWindows/issues/1738

Just to makes things clear: update procedure is on the AG for Windows/Mac side, that's why I moved it.
