### ISSUE TITLE
onhelp.me - Assistant's style is visible on the page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#190]
@seanl-adg commented on [Wed Dec 27 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/2071)

Source: https://github.com/AdguardTeam/AdguardAssistant/issues/164, https://github.com/AdguardTeam/AdguardFilters/issues/8946

---

@ameshkov commented on [Wed Jan 03 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2071#issuecomment-354879489)

@seanl-adg what's causing it?

---

@seanl-adg commented on [Wed Jan 03 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2071#issuecomment-354906936)

`GM_addStyle` is adding a `style` tag to the `body`, and the website applies a style `body > * { display: block; }`

---

@ameshkov commented on [Wed Jan 03 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2071#issuecomment-355005321)

What would be the proper fix? Adding `display: none` or adding to the `documentElement`

**Comment by 4-life** [comment]
Fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/3239c86d1b052015ff774ab1e1012c3740b16001
