### ISSUE TITLE
Assistant icon size problem on thefaceporn.com (NSFW)

### ISSUE THREAD

**Issue by adreporter01** [AdguardTeam/AdguardAssistant#191]
On this site (thefaceporn.com) Assistant icon not showning correctly. 
Browser version: Firefox nightly
Position: Top left

Icon size: small

<details>

![screenshot_1105](https://user-images.githubusercontent.com/36031501/36429329-dce141a8-166b-11e8-9dc9-9e54fd41afe6.png)
</details>

Icon size: large

<details>

![screenshot_1107](https://user-images.githubusercontent.com/36031501/36429351-ed62bc82-166b-11e8-8ea9-caa415de81f5.png)
</details>

**Comment by ameshkov** [comment]
plz use spoilers for this stuff

**Comment by adreporter01** [comment]
The same problem on the following site:
recwebcam.com

**Comment by 4-life** [comment]
Fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/eb8ae2601bfad7b1c4a380a1745943afc77fb98f
