### ISSUE TITLE
No Assistant icon on "ahaber.com.tr"

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardAssistant#192]
website: https://www.ahaber.com.tr/

There is no assistant icon on the website. I am using latest Firefox Beta 59 with AdGuard for Windows (Nightly)
Edit: The icon not visible on Edge browser, as well.

**Comment by ameshkov** [comment]
Hi! What exact version of Assistant?

**Comment by bkrucarci** [comment]
@ameshkov Sorry, it is working fine now. I do not know why I encounter such temporary problems.
