### ISSUE TITLE
X

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardAssistant#193]

**Comment by ameshkov** [comment]
> Try blocking an ad, move the slide, toggle with the preview and slider options, the slider resets to minimum.
> Asst 4.1.5

Confirmed, thank you!

**Comment by 4-life** [comment]
It's not a bug

**Comment by ameshkov** [comment]
@4-life not a bug, but it'd be better to not reset the position after preview.

**Comment by The-Commissioner** [comment]
The slider resetting it's position is an intended feature then? Wow.
Nice feature making me go over again to that position and deciding where I had fixed the slider before I used the preview feature.

**Comment by ameshkov** [comment]
Intended by a developer, but needs to be changed :)

**Comment by The-Commissioner** [comment]
I'm really interested in knowing the reason why it was intended? What purpose it fulfilled?

**Comment by The-Commissioner** [comment]
I will wait 4 more days for the answer.

**Comment by ameshkov** [comment]
> I'm really interested in knowing the reason why it was intended? What purpose it fulfilled?

Afaik, this seemed better for the code design. Obviously, it is not user-friendly, but it's not enough to mark it as a bug.
