### ISSUE TITLE
Pink Adblock Warning Removal screen on site: www.allaboutphones.nl

### ISSUE THREAD

**Issue by gvanosch12** [AdguardTeam/AdguardAssistant#2]
Hello,

I see on the website www.allaboutphones.nl a pink message about that i,m using an Adblocker,please whitelist us,i have already installed the annoyance filterrule and the rule adblock warning removallist,and the anti-adblock killer reek rule,but none of these rules are taking effect.
Can you please add the site www.allaboutphones.nl  to the Annoyance filter rule,that will remove this pink adblock warning removal screen on this site(see screenshotlinks)
I have no extra filterrules at the Userfilter on the Adguard Application.

Kindly regards,

Geert Van Osch

![schermopname 98](https://cloud.githubusercontent.com/assets/19804873/24296178/46d11e6e-109e-11e7-9e85-7cf9cc914d60.png)
![schermopname 99](https://cloud.githubusercontent.com/assets/19804873/24296248/9b5a3f06-109e-11e7-9dcd-1911d194412c.png)
![schermopname 100](https://cloud.githubusercontent.com/assets/19804873/24296260/b19673e8-109e-11e7-9272-818596dacb59.png)

https://www.allaboutphones.nl/

http://www.awesomescreenshot.com/image/2325610/47c03b3417bd2d20e5088df182b4b4b5

 http://www.awesomescreenshot.com/image/2324207/f3c3a98add8e9da4adf4e4d15bf434c7       
 
@Stillness-2 @sfionov

**Comment by vbagirov** [comment]
@gvanosch12 its better to post about such things in the https://github.com/AdguardTeam/AdguardFilters/issues/ repository.

**Comment by vbagirov** [comment]
Duplicate for https://github.com/AdguardTeam/AdguardFilters/issues/4664
