### ISSUE TITLE
New Assistant doesn't work with touch on Edge

### ISSUE THREAD

**Issue by miguedevel** [AdguardTeam/AdguardAssistant#20]
When tapping on the new Assistant icon, the flyout doesn't show. Moreover, after tapping on the Assistant icon and then tapping anywhere else on the webpage, the icon will just move to the tapped location.

Here are the related touch settings in about:flags :

![image](https://cloud.githubusercontent.com/assets/26647325/25598021/60b29f9a-2ea0-11e7-948b-809a100b114f.png)

**Comment by ameshkov** [comment]
@miguedevel nice, thank you for reporting it!
