### ISSUE TITLE
Assistant doesn't save its custom position on vk.com

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardAssistant#201]
STR

1. go to vk.com
2. drag and drop Assistant icon to any place on the page
3. reload the page or close/open new vk.com tab

Expected result: Assistant remember its position

Actual result: Assistant icon is in bottom right corner

**Comment by ameshkov** [comment]
1. Use GM storage to store the custom position.
2. We should add a new checkbox to the Assistant settings: `All websites / this website only`

**Comment by zebrum** [comment]
@ameshkov We should clarify that this option will reset all previous custom assistant settings 

![up03_bdiln](https://user-images.githubusercontent.com/23637588/40179784-ccbdef7c-59ed-11e8-870a-0c34220d70a2.png)

**Comment by ameshkov** [comment]
@zebrum let's try. @4-life add a help text under this option (with a gray text, font size fewer by 2 px).

**Comment by 4-life** [comment]
Fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/b6c6b54724c1397f92f3a0e73bb7eb488cf2b7e7

**Comment by rkmyowin** [comment]
Change a Battery charger for
