### ISSUE TITLE
Assistant does not show up in Opera Neon 1.0.2531.0

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardAssistant#205]
Reproduced with both release and nightly 6.3.948.3171. Ads are filtered which is reflected in the filtering log, but the Assistant is missing on all pages.

![image](https://user-images.githubusercontent.com/15856304/38552715-f36523da-3cb4-11e8-9bf7-1ce12e390183.png)

**Comment by 4-life** [comment]
Fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/03376a3f71c2669427ce1a34697e3b5c90d14e7c
