### ISSUE TITLE
"Block ads" tool's buttons are displaced

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#207]
@vozersky commented on [Wed Apr 11 2018](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/999)

### Steps to reproduce
1. Open gmail.com
2. Try to block hangouts div
3. Click on "Advanced settings"

### Actual behavior
"Select another element" "preview" and "block" Buttons are displaced

### Screenshot

https://uploads.adguard.com/up05_wzaxg.png

### Your environment

* AdGuard AdBlocker extension version: 2.9.2
* Chrome  65.0.3325.181

**Comment by 4-life** [comment]
Fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/093ec82f03c279678760b6fa2dadafbd5e271d92
