### ISSUE TITLE
Allow user to disable Assistant on certain web pages

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardAssistant#209]
As reported by user 1744022,

> Please make it possible to completely remove the AdGuard Assistant
icon from a specific web page.

It seems like the user would like to hide the Assistant icon without impacting the protection status. The FR has been sent from ADG for Windows application, ver 6.2.437.2171

**Comment by vozersky** [comment]
@akmLaVx  You can use  `@@||example.com^$extension`
