### ISSUE TITLE
Add 'Do not show this window' option

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardAssistant#21]
![image](https://cloud.githubusercontent.com/assets/15856304/25606984/131d7232-2f1d-11e7-9d01-579782b72edc.png)

We received a suggestion to add the option to block this kind notifications and the ability to toggle it via the pop-up or Adguard ad blocker settings section.

**Comment by vozersky** [comment]
@evgeniy-ADG 

You can disable all Adguard notifications through Advanced settings, just uncheck:
![image](https://cloud.githubusercontent.com/assets/17472907/25616828/9b51764c-2f47-11e7-9ec7-0fea89704821.png)

Or the user wants to hide only this particular one?
