### ISSUE TITLE
Assistant not clickable on solarmoviefreez.com/list/movies.html

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardAssistant#210]
Visit http://solarmoviefreez.com/list/movies.html and try to click on the assistant... nothing will happen. No issues on the main page (http://solarmoviefreez.com/).

Windows 10 x64
Chrome 67.0.3396.10
Assistant 4.1.12
AdGuard for Windows 6.3.977.3229

**Comment by BlazDT** [comment]
Fixed in filter list.

@ dev
Please change the Assistant, so it is always the top-layer as in this case the ad put it on a click eventListener which intercepts the click everytime.

**Comment by 4-life** [comment]
Fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/2bb6a832b9c66f3defc7f36528e4c3800435ffc7#diff-3595e5c741d5ec635c69a2f7d73648b6R14
