### ISSUE TITLE
Video Full-Screen Asystent AdGuard occurs

### ISSUE THREAD

**Issue by Mo-norn** [AdguardTeam/AdguardAssistant#212]
The whale browser(Chromium) is being used.
(https://whale.naver.com/en/)

Symptoms occur after the version 4.1.12 update.

On the full video screen Asystent AdGuard will also be shown above.

![qqqqqq](https://user-images.githubusercontent.com/34658160/39093660-0fb89e06-465e-11e8-905a-50c241ea7801.png)
http://2tcafe.com/bbs/board.php?bo_table=c_video

**Comment by vozersky** [comment]
reproduced
make sure you open http://2tcafe.com/bbs/board.php?bo_table=c_video and watch videos exact page

**Comment by 4-life** [comment]
Fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/d8a4802f9c10f42788d646b458eb4cee7c8f90fb
