### ISSUE TITLE
[Extension] Assistant window can be hidden by rule

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardAssistant#213]
Assistant window can be hidden by rule, please check and modify Assistant. The general hiding rules had a higher priority than the assistant.

https://camo.githubusercontent.com/30233d712a98aa22597a5bb5b5119abd8a8110cd/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f7a4d655041734e2e706e67

@ devs
Disable the following rule in English filter to reproduce and visit one of the sites, I reproduced it on *jerusalemonline.com*:

`coed.com,collectivelyconscious.net,colourlovers.com,connectedly.com,convert-me.com,convertcase.net,crackberry.com,dailygalaxy.com,datpiff.com,destructoid.com,dietlast.com,diffen.com,drudgereport.com,dwatchseries.to,easybib.com,eurweb.com,freewarefiles.com,fullmatchesandshows.com,gelbooru.com,genfb.com,getinmybelly.com,gorillavid.in,grammarist.com,imagepearl.com,imore.com,indiewire.com,jerusalemonline.com,jewsnews.co.il,jpost.com,kizi.com,kshowonline.com,magnetdl.com,mmorpg.com,movpod.in,nba-stream.com,newsarama.com,nydailynews.com,omgcheckitout.com,opensubtitles.org,phonesreview.co.uk,playbill.com,readmng.com,roadracerunner.com,robinwidget.com,rule34.xxx,sh.st,sportspickle.com,teslacentral.com,tetrisfriends.com,the4thofficial.net,thebarchive.com,thefreethoughtproject.com,toptenz.net,trifind.com,unblckd.org,uproxx.com,usherald.com,veteranstoday.com,videotoolbox.com,vrheads.com,watchseries.sk,windowscentral.com,wnd.com,xda-developers.com#@#[style*="block !important"]`

**Comment by 4-life** [comment]
@ameshkov this inline style is already present

**Comment by ameshkov** [comment]
> @ameshkov this inline style is already present

That's my point - do **not** add it

**Comment by 4-life** [comment]
fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/4aff8db7280cf5064192c3f8ce1fe6d91df08bf6
