### ISSUE TITLE
Error when clicking on Assistant at cloud.mail.ru

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#215]
Adguard 6.3.1028.3331
Assistant 4.1.12

**STR:**
1. Open cloud.mail.ru
2. Try to open Assistant's menu

**Actual result:**
Nothing happens

![screen shot 2018-04-23 at 12 00 45](https://user-images.githubusercontent.com/17472907/39119764-5e783bcc-46f5-11e8-9088-b7a9aed342f2.png)
![screen shot 2018-04-23 at 12 00 33](https://user-images.githubusercontent.com/17472907/39119765-5eca614a-46f5-11e8-9535-06cc2b9261a7.png)

**Comment by ameshkov** [comment]
@vozersky can you still reproduce the issue?

**Comment by vozersky** [comment]
Yes, I can.

Adguard 6.3.974
Assistant 4.1.12

**Comment by vozersky** [comment]
Looks like it's only reproducible with 6.3.1028.3331 Nightly
Assistant 4.1.12

**Comment by 4-life** [comment]
Yes, it's only reproducible with 6.3.1028.3331 Nightly
![123](https://user-images.githubusercontent.com/10114517/39861430-3ab2a86a-5449-11e8-9acc-81177538c398.png)

**Comment by vozersky** [comment]
@4-life @adbuker

**Comment by ameshkov** [comment]
@seanl-adg please check it asap, could it be that the userscript wrapper does not fully protects the browser APIs in the nightly build?

**Comment by seanl-adg** [comment]
Caused by a JS rule:
```
nnm-club.tv,rustorka.com,pise4ka.net,nnm-club.me,nnm-club.ws,nnmclub.to,onlainfilm.ucoz.ua,rutor.is,baskino.club,rutor.info,nnm.me,korzik.net,seasonvar.ru,rsload.net,nnm-club.me,nnmclub.to,rustorka.com,auto.mail.ru,horo.mail.ru,realty.mail.ru,health.mail.ru,afisha.mail.ru,cloud.mail.ru,otvet.mail.ru,pogoda.mail.ru,sport.mail.ru,tv.mail.ru,torg.mail.ru,cars.mail.ru,hi-tech.mail.ru,free-torrent.org,free-torrents.org,ukrinform.ru,radikal.ru,trackeroc.ru,trackerock.ru#%#window.WebSocket = undefined;
```

**Comment by ameshkov** [comment]
@seanl-adg what about console output from the `raven.min.js`?
https://github.com/AdguardTeam/AdguardAssistant/issues/215#issuecomment-387995641

Does it override console?

**Comment by seanl-adg** [comment]
It appears that `raven.min.js` overrides `EventTarget.prototype.addEventListener` and catches errors thrown from event handlers.

**Comment by ameshkov** [comment]
> It appears that raven.min.js overrides EventTarget.prototype.addEventListener and catches errors thrown from event handlers.

Any idea on how to protect ourselves from that?

**Comment by seanl-adg** [comment]
We may make the assistant userscript run at document start and keep references to native objects, or create an iframe and do smth like `iframe.contentWindow.EventTarget.prototype.addEventListener`

**Comment by ameshkov** [comment]
@vozersky plz re-test this issue once new AG nightly is out.

**Comment by ameshkov** [comment]
@vozersky the issue will go away once we do #224
