### ISSUE TITLE
Assistant doesn't work on rustorka.com

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardAssistant#216]
http://rustorka.com/forum/index.php
AdGuard beta 6.2
Assistant 4.1.12

https://uploads.adguard.com/up03_8t933.png

**Comment by 4-life** [comment]
Same problem like in https://github.com/AdguardTeam/AdguardAssistant/issues/215

**Comment by ameshkov** [comment]
We'll need to re-test it with a new nightly
