### ISSUE TITLE
Assistant breaks heise.de in Firefox and Edge

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardAssistant#217]
Assistant 4.1.12
AdGuard 6.3.977.3229

To reproduce go here - https://www.heise.de/newsticker/classic/
There is no scrollbar and website is wrongly scaled.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/39326434-39db5630-4995-11e8-905e-43271d735c1e.png)

</details>
<br>

https://github.com/AdguardTeam/AdguardFilters/issues/10716#issuecomment-371306710

**Comment by ameshkov** [comment]
@4-life try reproducing it with AdGuard 6.3 and Edge

**Comment by 4-life** [comment]
assistant do not start with AdGuard 6.3 and Edge browser. The page is not breaks

**Comment by ameshkov** [comment]
> assistant do not start with AdGuard 6.3 and Edge browser

And that's not okay as well

**Comment by AdamWr** [comment]
I added `@@||heise.de^$extension` to English filter as a temporary solution, so it is the reason why assistant is disabled on heise.de.

**Comment by BlazDT** [comment]
Another case where Extension breaks the site in FF:

https://github.com/AdguardTeam/AdguardFilters/issues/16082

Added temp. exclusion.

**Comment by AdamWr** [comment]
With the latest nightly 6.3.1154.3583 and Assistant 4.2.3 I can't reproduce this issue anymore.

**Comment by 4-life** [comment]
@ameshkov in all browsers the userscript wrapper does not start at all. I checked it on last nightly version

**Comment by ameshkov** [comment]
@4-life that's due to the rule in the Base filter. Disable it in the Base filter and re-check it.

**Comment by ameshkov** [comment]
I guess we can remove this rule now.

**Comment by AdamWr** [comment]
If we remove this rule then website will be broken with AdGuard 6.2.

**Comment by ameshkov** [comment]
Hm, I thought the issue breaks it in v6.3 only.

**Comment by ameshkov** [comment]
Yeah, you're right, we should remove it only after the v6.3 release.

**Comment by AdamWr** [comment]
No, with AG 6.2 it's also broken.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/41036770-6d5ee762-6991-11e8-9a8e-b1c83e54414c.png)

</details>
