### ISSUE TITLE
http://gogoanime.bz/anime/hitori-no-shita-the-outcast-2nd-season/

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardAssistant#218]
AdGuard assistant does not work on http://gogoanime.bz/anime/hitori-no-shita-the-outcast-2nd-season/.

**Comment by TheHasagi** [comment]
Reproduced on 6.2\6.3 (BETA).
Windows 10 x64, Chrome,Edge,FF.

**Comment by TheHasagi** [comment]
Browser console output:
# 
Adguard Assistant Beta.user.js:3430 Page is iframe: https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fgogoanime.bz%2F&amp;width=340&height=500&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=false&appId=112434389463499
print @ Adguard Assistant Beta.user.js:3430
error @ Adguard Assistant Beta.user.js:3451
validatePage @ Adguard Assistant Beta.user.js:4204
checkRequirements @ Adguard Assistant Beta.user.js:7047
show @ Adguard Assistant Beta.user.js:7006
adguardAssistantExtended @ Adguard Assistant Beta.user.js:7504
(anonymous) @ Adguard Assistant Beta.user.js:7538
(anonymous) @ Adguard Assistant Beta.user.js:7541
(anonymous) @ Adguard Assistant Beta.user.js:3
(anonymous) @ Adguard Assistant Beta.user.js:3
settings.scriptInfo.script.options.run-at @ userscripts.js?ts=63660911741703&name=Adguard Assistant Beta&name=Popup Blocker by AdGuard (Beta):40
d @ userscripts.js?ts=63660911741703&name=Adguard Assistant Beta&name=Popup Blocker by AdGuard (Beta):35
c @ userscripts.js?ts=63660911741703&name=Adguard Assistant Beta&name=Popup Blocker by AdGuard (Beta):35
Adguard Assistant Beta.user.js:3430 2018-05-03T10:48:02.015Z: Environment doesn't satisfy requirements, so don't show Adguard
#

**Comment by 4-life** [comment]
Fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/0c8612b56beafd9058acae76285670539de5e7b8
