### ISSUE TITLE
Swap the 'MIN' and 'MAX' labels on the 'Block ad' slider

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardAssistant#22]
Screenshot:
https://www.screencast.com/t/tINY6KMY

**Comment by Mizzick** [comment]
We had a discussion on this already. "Min" and "Max" associated with zoom here.

**Comment by Mizzick** [comment]
https://www.dropbox.com/s/fl6trian1kzc7c8/Screenshot%202017-05-02%2021.16.05.png?dl=0
hah, but it's different.

**Comment by ameshkov** [comment]
Btw, why do we have different translation in extension and in the assistant?

**Comment by vozersky** [comment]
@ameshkov It has been already fixed in extension and old Assistant, no idea where did it come from.
