### ISSUE TITLE
Assistant clicks through a banner

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#220]
**Issue 1:**

Video:
https://uploads.adguard.com/up04_szj3u_2018-05-05_13.40.34.mp4

Selecting a banner on sports.ru leads to a banner click

**Issue 2**
When the element is selected, second click on it is not suppressed.

**Comment by 4-life** [comment]
Fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/df654bde705e50a0f7d3cbce83d64b81dce9fef0
