### ISSUE TITLE
Consider changing `run-at` to `document-start`

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#224]
So that we could solve numerous issues with websites overriding native APIs like this (actually, there're more):
https://github.com/AdguardTeam/AdguardAssistant/issues/215#issuecomment-388031760

In this case, we'll need to postpone the script execution manually just like it's done in the userscript wrapper.

**Comment by 4-life** [comment]
Issue not for assistant rep

**Comment by ameshkov** [comment]
This IS for assisstant repo

**Comment by 4-life** [comment]
Fixed by https://github.com/AdguardTeam/AdguardAssistant/commit/4474f95b25a55fc6795b461a2fc190ac0828289c
