### ISSUE TITLE
No assiant on samsunhaber.com

### ISSUE THREAD

**Issue by adreporter01** [AdguardTeam/AdguardAssistant#225]
No assiant on samsunhaber.com

**Comment by vozersky** [comment]
browser, version?

**Comment by vozersky** [comment]
still no luck

**Comment by adreporter01** [comment]
@vozersky  AG Assitant already shown:

![screenshot_27](https://user-images.githubusercontent.com/36031501/39954783-76da47e6-55cd-11e8-8c9d-f1b5c67dd74b.png)

**Comment by vozersky** [comment]
ok, great 👍
