### ISSUE TITLE
No assistant on fotomac.com.tr

### ISSUE THREAD

**Issue by adreporter01** [AdguardTeam/AdguardAssistant#226]
No assistant on fotomac.com.tr

**Comment by adreporter01** [comment]
No information about AG Assistant

![screenshot_19](https://user-images.githubusercontent.com/36031501/39913863-fbab0f22-550b-11e8-8bba-a5260d79cf99.png)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #2200](https://github.com/AdguardTeam/AdguardForWindows/issues/2200) via [**ZenHub**](https://www.zenhub.com/)
