### ISSUE TITLE
No assistant on orjinalsozler.com

### ISSUE THREAD

**Issue by adreporter01** [AdguardTeam/AdguardAssistant#227]
OS: Windows 10
Browser: Google chrome latest dev
Ag version: Nightly

![screenshot_130](https://user-images.githubusercontent.com/36031501/40098151-0f2c7382-58eb-11e8-8fc1-f71fbd571e06.png)

**Comment by ameshkov** [comment]
All three issues you've filed are basically the same -- HTTPS filtering does not work for this and that domain. 

Could you please help us figure out why is that happening?
https://github.com/AdguardTeam/AdguardForWindows/issues/2200#issuecomment-388750359

**Comment by ameshkov** [comment]
@adreporter01 we'll need the debug log (as explained here: https://github.com/AdguardTeam/AdguardForWindows/issues/2200#issuecomment-388750359) recorded while reproducing this issue.
