### ISSUE TITLE
Assistant settings can't be saved in browsers sometimes

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardAssistant#228]
Actual result: When tapping on 'Save setting' button nothing happens

Expected result: settings has been saved, window is closed

Steps to reproduce are uncleared so far, but the issue happens from time to time
![up03_p9mp1](https://user-images.githubusercontent.com/23637588/40172450-362ee428-59d7-11e8-87aa-93595a78aa03.png)

on latest nightly build 6.3.1052.3379
Chrome  66.0.3359.181
Firefox 59.0.2

**Comment by 4-life** [comment]
This does not apply to current builds of assistant
