### ISSUE TITLE
rsload.net

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardAssistant#229]
@adguard-bot commented on [Wed May 23 2018](https://github.com/AdguardTeam/AdguardFilters/issues/16750)

### Issue URL (Incorrect Blocking)
[https://rsload.net/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Frsload.net%2F)
### Comment
> не работает помошник справа внизу страници нажимаеш на него ничего не происходит

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/7fdF54G.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.3.974.3223
Browser: | oldFirefox
AdGuard driver: | TDI
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Block third-party Authorization header, Self-destructing first-party cookies(), Self-destructing third-party cookies(), Disable cache for third-party requests, Block WebRTC, Block Push API, Block Location API, Block Flash, Block Java
Filters: | Russian,<br>English,<br>Spyware,<br>Social media,<br>Experimental,<br>German,<br>Japanese,<br>Dutch,<br>Spanish/Portuguese,<br>Filter unblocking search ads and self-promotion,<br>Mobile Ads,<br>Turkish,<br>Annoyances,<br>Simplified domain names,<br>French,<br>hufilter,<br>Anti-Adblock Killer | Reek

---

@Alex-302 commented on [Wed May 23 2018](https://github.com/AdguardTeam/AdguardFilters/issues/16750#issuecomment-391448167)

@zebrum @vozersky

**Comment by zebrum** [comment]
![image](https://user-images.githubusercontent.com/23637588/40475303-ed21b9c2-5f49-11e8-97f8-2b31ebbc15d9.png)

**Comment by 4-life** [comment]
After Firefox update to 60 this bug has gone

**Comment by 4-life** [comment]
@ameshkov the problem is in wrapper
