### ISSUE TITLE
Assistant icon not displayed

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardAssistant#230]
@dangkyokhoang commented on [Fri May 25 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2222)

The Assistant icon can't be displayed on this site: [https://dkhwebapp.tk/](https://dkhwebapp.tk/)
because the `'unsafe-inline'` style directive injected by AdGuard is ignored (as a hash-source specified) and the style tag created by the AdGuard Assistant script doesn't have the `nonce` attribute.

<details><summary>Screenshot:</summary>

![Error message](https://user-images.githubusercontent.com/14311741/40529287-5499eabe-601e-11e8-86ec-04201a79a133.png)
Style blocked

![No nonce value](https://user-images.githubusercontent.com/14311741/40530201-0168035e-6022-11e8-891c-6adc6043eca2.png)
![No nonce value](https://user-images.githubusercontent.com/14311741/40530202-01a97dd4-6022-11e8-8453-238ea37e72c3.png)
The style tag doesn't have the `nonce` attribute

</details>

**Comment by ameshkov** [comment]
You must add `nonce` to the style tags.
