### ISSUE TITLE
Can not make Adguard Assistant small all websites 6.3.1117.3509 won't save

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#233]
@Steve1209 commented on [Thu May 31 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2231)

### Steps to reproduce

1. Open Adguard Assistant settings and choose small and all websites.
2.
3.
4.

### Expected behavior
<should save

### Actual behavior
< it won't save

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Chrome Version 66.0.3359.181 (Official Build) (64-bit)
* Operating system Windows 10 Home V1803 OS build 17134.81

---

@ameshkov commented on [Fri Jun 01 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2231#issuecomment-393679959)

Hm, I cannot reproduce the issue. Could you please check what exact Assistant version are you using?

---

@ameshkov commented on [Fri Jun 01 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2231#issuecomment-393681356)

My bad! This is a bug of the current Assistant version.

**Comment by Steve1209** [comment]
My Adguard Assistant is 4.2.2
