### ISSUE TITLE
[Bug] no assistant on heise.de

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#234]
@Vincent-Michael commented on [Tue Jun 05 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2239)

![](https://i.imgur.com/pRvHmiv.jpg)
![](https://i.imgur.com/9I7NypY.png)

## Your environment
Adguard 6.3.1154.3583
Browser: Vivaldi 59
OS: Windows 10, v.1803, build 17134.81

**Comment by AdamWr** [comment]
I think it's related to this issue - https://github.com/AdguardTeam/AdguardAssistant/issues/217 and this "exception" - `@@||heise.de^$extension`

**Comment by ameshkov** [comment]
Uh, indeed a duplicate.

Could you please check #217 with the new nightly?

**Comment by AdamWr** [comment]
Done - https://github.com/AdguardTeam/AdguardAssistant/issues/217#issuecomment-394853199

**Comment by TheHasagi** [comment]
https://www.heise.de/ - No Assistant.
