### ISSUE TITLE
Assistant breaks login frame on gog.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardAssistant#236]
Assistant 4.2.4
AdGuard 6.3.1154.3583

To reproduce go here - https://www.gog.com/ and click on "Sign in" button.
Try to log in. It should works, but it just reload login frame.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/41046047-efe98076-69a9-11e8-9a5f-e34343c04936.png)

</details>
<br>

As a temporary solution I added `@@||login.gog.com^$extension`, so please disable it before checking it.

https://github.com/AdguardTeam/AdguardFilters/issues/17631

**Comment by 4-life** [comment]
Problem with captcha. Same issues on websites:
https://adbtc.top/surf/
http://www.taxi-money.info/clicks/surfing
http://www.wmmail.ru/index.php?cf=mail-viewpmail

**Comment by ameshkov** [comment]
@adbuker this might be AG4Win bug as well

**Comment by AdamWr** [comment]
It works fine with the latest Assistant Beta 4.2.5.
I removed rules for `gog.com`, `spaste.com` and `kissasian.ch` with `$extension`

**Comment by ameshkov** [comment]
Awesome, thank you!
