### ISSUE TITLE
Extension prevents captcha solving ...

### ISSUE THREAD

**Issue by simaelena** [AdguardTeam/AdguardAssistant#237]
Extension prevents captcha solving on several sites causing error 'wrong captcha'. When extension is disabled problem disappears.

**Comment by ameshkov** [comment]
What exact websites?

**Comment by simaelena** [comment]
e.g.
https://adbtc.top/surf/
http://www.taxi-money.info/clicks/surfing
http://www.wmmail.ru/index.php?cf=mail-viewpmail
Manually installed previous release 4.1.12 solved the problem, but extension forced to update and problem returned.

**Comment by 4-life** [comment]
Same issue https://github.com/AdguardTeam/AdguardAssistant/issues/236
