### ISSUE TITLE
Assistant icon is not centred inside circle.

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardAssistant#241]
On Mac, Google Chrom: 67.0.3396.87

![2018-06-22 15 14 26](https://user-images.githubusercontent.com/12689/41776153-4e00ac8e-762f-11e8-8160-cac160b9fce1.png)

**Comment by ameshkov** [comment]
Icons:
[assistant.zip](https://github.com/AdguardTeam/AdguardAssistant/files/3240709/assistant.zip)
