### ISSUE TITLE
Incorrect exception rule is created with Assistant

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#242]
@vozersky commented on [Sat Jun 23 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2265)

### Steps to reproduce

1. Disable "Use localhost for injections"
2. Go to"https://meduza.io"
3. Open Adguard Assistant's menu on the page and disable filtering on the website.

### Expected behavior
`@@||meduza.io^$important,document,~extension` is created and added to User filter

### Actual behavior
`@@||injections.adguard.com^$important,document,~extension` is created and added to User filter

### Your environment
* Adguard 6.3.1276.3827 
*  Chrome 67.0.3396.87
* Win 10, 1803

**Comment by ameshkov** [comment]
100% this is a Win version bug
