### ISSUE TITLE
Assistant doesn't work  in Safari when cookies disabled

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardAssistant#244]
@adguard-bot commented on [Tue Jul 03 2018](https://github.com/AdguardTeam/AdguardFilters/issues/19203)

### Issue URL (Incorrect Blocking)
[https://www.t-online.de](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.t-online.de)
### Comment
> when I block all cookies in Safari the window from AdGuard ist not to see on the Pages any more so that I can block something. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/sf7Rqik.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Mk6k6cm.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 1.5.8
Browser: | Safari
Filters: | Russian,<br>English,<br>Spyware,<br>German,<br>Japanese,<br>French,<br>EasyList,<br>EasyPrivacy
Other extensions used: | Bitdefender

---

@Alex-302 commented on [Wed Jul 04 2018](https://github.com/AdguardTeam/AdguardFilters/issues/19203#issuecomment-402504135)

@zebrum please take a look. Can be reproduced with this option:
![image](https://user-images.githubusercontent.com/8361299/42284259-a0d71806-7fb4-11e8-8fe1-e4b5d376cf4e.png)

**Comment by ameshkov** [comment]
@zebrum this must be re-tested when we start using the new Assistant on Mac version
