### ISSUE TITLE
Grammar mistake from WoT report.

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardAssistant#246]
OS: Windows (latest updates) 10.0.17134
AdGuard version 6.3 (latest Nightly).
Grammar mistake from WoT report.

![image](https://user-images.githubusercontent.com/37797229/42758287-b8017f84-890b-11e8-929c-be1936ea49ef.png)

**Comment by 4-life** [comment]
Please update WOT extension to v1.1.3
