### ISSUE TITLE
Assistant not clickable on plg.ovakode.com

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardAssistant#248]
https://plg.ovakode.com/

![image](https://user-images.githubusercontent.com/10995998/43090340-67dc3606-8ea7-11e8-9f16-b1d520d6f8a1.png)

Version 4.3.2
Chrome 69.0.3493.3

**Comment by BlazDT** [comment]
Can click it fine in my Chrome on that site.

**Comment by danidoedel** [comment]
@BlazDT Disable these rules: https://github.com/AdguardTeam/AdguardFilters/commit/f01fcf21611a484da8e0d6976c2f93d56be81a47

**Comment by karina-archazh** [comment]
Assistant and Popup blocker works fine on this website without any filters.
Please check if your Popup blocker version.
<details>

![image](https://user-images.githubusercontent.com/41899455/48723660-47b26f00-ec38-11e8-85ff-72d0cd40b694.png)

</details>
