### ISSUE TITLE
realist.online - assistant is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardAssistant#249]
@adguard-bot commented on [Tue Jul 24 2018](https://github.com/AdguardTeam/AdguardFilters/issues/20161)

### Issue URL (Ads)
[https://realist.online/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Frealist.online%2F)
### Comment
> и не работает помошник адгуарда при нажатии ничего не происходит

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/8mo5m4k.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.3.1399.4073
Browser: | oldFirefox
AdGuard driver: | TDI
Filters: | Russian,<br>English,<br>Spyware,<br>Social media,<br>Experimental,<br>German,<br>Dutch,<br>Filter unblocking search ads and self-promotion,<br>Mobile Ads,<br>Turkish,<br>Annoyances,<br>Simplified domain names,<br>French,<br>hufilter,<br>Anti-Adblock Killer | Reek

---

@Alex-302 commented on [Tue Jul 24 2018](https://github.com/AdguardTeam/AdguardFilters/issues/20161#issuecomment-407469722)

**Comment by BlazDT** [comment]
Probably related issue, but with iOS:
https://github.com/AdguardTeam/AdguardFilters/issues/20923
