### ISSUE TITLE
[Feature Request] Display in Assistant the count of ads blocked on the current page

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardAssistant#25]
Original thread:
https://forum.adguard.com/index.php?threads/19637/#post-135859

**Comment by GauthierPLM** [comment]
This would be a nice addition. Having a list of blocked elements (maybe taken from Adguard' filtering logs) would also be a good addition to diagnostic issues or to have a better understanding of what the current website is doing.

Going further, we could even imagine having a list of rules applied to the current page and the possibility to disable them individually. For example, as a developer, I might be interested to disable filtering of Google Analytics while I work on my website. Being able to do it conveniently from the Assistant would add a lot of value to the assistant.
