### ISSUE TITLE
Assistant icon no longer hidden during full screen video

### ISSUE THREAD

**Issue by d0x360** [AdguardTeam/AdguardAssistant#252]
Ever since (i believe) the beta update prior to the one released last week ive noticed that the assistant icon no longer becomes hidden when viewing full screen video in the browser.

It used to go away immediately but for some reason it doesn't anymore and i cant figure out why or how to make it go away aside from disabling it altogether.

**Comment by northis** [comment]
same issue https://github.com/AdguardTeam/AdguardForWindows/issues/2309

**Comment by d0x360** [comment]
It's long since fixed...just remove the post.  I checked the list when I made it and didn't see any other repo
