### ISSUE TITLE
Unable to block the element on https://web.de

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardAssistant#253]
It is unable to block an element with AdGuard Assistant by "Block ads on this website" function.

![image](https://slack-imgs.com/?c=1&url=https%3A%2F%2Fuploads.adguard.com%2Fup22_ktbm2.png)

**Comment by BlazDT** [comment]
Working fine here. Can you still reproduce @TheHasagi?

**Comment by TheHasagi** [comment]
It is working fine for now.
