### ISSUE TITLE
Filtering status color indication

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#254]
@ClassicUA commented on [Sat Sep 08 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2324)

Добрый день.

Есть предложение сделать щит иконки помощника красного цвета при отключенной фильтрации на определённом сайте.

---

@Alex-302 commented on [Sat Sep 08 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2324#issuecomment-419638934)

Красный - цвет аварии. Лучше серый.

---

@ClassicUA commented on [Sat Sep 08 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2324#issuecomment-419639208)

Можно и серый.

---

@ameshkov commented on [Thu Sep 13 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2324#issuecomment-420823342)

Спасибо! Перенесу, пожалуй, в релевантный репозиторий.

**Comment by soundoctor** [comment]
PLEASE -- as long as it can be easily seen! Perhaps a purple. THANK YOU !!!
