### ISSUE TITLE
Assistant still appears on artiway.com.tr 

### ISSUE THREAD

**Issue by Elenve** [AdguardTeam/AdguardAssistant#255]
Our customer added a rule to exclude the website from filtering (@@||artiway.com.tr$document), but the icon of the Assistant still appears when logged in.

<details>

![image](https://user-images.githubusercontent.com/17320558/45504428-25105f80-b78a-11e8-95dc-c590cbd894e6.png)

</details>

Adding the website to the HTTPS exceptions didin’t help.

More info here: 461686

**Comment by june8-o** [comment]
A sample video: https://youtu.be/d9im1vYcyFk

**Comment by zebrum** [comment]
can't repro
Please try to disable other browser extension and check if the issue happens.

**Comment by june8-o** [comment]
I disabled all extensions but the problem still exists on both browsers Safari and Firefox.
