### ISSUE TITLE
fanfox.net - Assistant not working correctly

### ISSUE THREAD

**Issue by im3or** [AdguardTeam/AdguardAssistant#257]
I have some blocked elements on fanfox which doesn't work when assistant is not not loading sometimes. This occurs occasionally so it is pretty bothersome. 

As you can see in the images, on the same site, same time but different tabs, that something is wrong.

Windows 7, Firefox, Adguard 6.3, Assistant 4.1.12

![screenshot00586](https://user-images.githubusercontent.com/30718972/46387114-d13acb80-c6e2-11e8-97da-65071c803759.jpg)
![screenshot00587](https://user-images.githubusercontent.com/30718972/46387115-d1d36200-c6e2-11e8-833f-1305a24cd4f2.jpg)

**Comment by ameshkov** [comment]
It's not just about Assistant. It looks as if AdGuard cosmetic rules aren't applied as well.

How often does it happen?
What needs to be done to resolve it when it happens?

**Comment by im3or** [comment]
It happens sometimes. Most of the time it is all right.
I don't know what needs to done to resolve, i basically just close the tab & open again the website & half the time it is resolved by that. 

This is totally a random problem as far as i am concerned. The new Adguard for windows (6.4) seems to be helping. Haven't had this problem often. But it is still there.

Will let you know if i figure out something on my end.

**Comment by im3or** [comment]
The temporary solution that i found for this is to USE Internet Explorer. This issue is NOT happening there, so for browsing fanfox i am using IE 11 temporarily. 
Firefox is my primary browser, please into the problem.

**Comment by im3or** [comment]
How did this got closed?

**Comment by im3or** [comment]
I installed Adguard browser extension in firefox so now where assistant fails to load, adguard extension works & blocks the ads. No need to fix this.
FYI this problem also started happening at kissanime.ru
