### ISSUE TITLE
New Assistant breaks Chrome Web Store

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardAssistant#26]
https://chrome.google.com/webstore/category/extensions

https://github.com/AdguardTeam/AdguardForWindows/issues/1730

**Comment by BooBerry** [comment]
It's the same issue as #18 

It should probably be renamed, as it doesn't affect just Docs, but the Chrome Web Store and Calendar.

**Comment by confessor-adguard** [comment]
Caused by overriding "en" function in the global scope.
