### ISSUE TITLE
Please add a placeholder to some phrases.

### ISSUE THREAD

**Issue by aalpatkina** [AdguardTeam/AdguardAssistant#261]
We need to use placeholders in the following strings on OneSky (after the preposition "to") because some languages have a different word order.

String Keys:

wot_bad_description.message
wot_poor_description.message
wot_unsatisfactory_description.message
wot_good_description.message
wot_excellent_description.message
and
wot_unknown_description.message

Example: This website has a bad reputation according to --> This website has a bad reputation according to [placeholder]

**Comment by lancelot-moon** [comment]
This website's reputation is not defined by

**Comment by lancelot-moon** [comment]
@ameshkov 
@Mizzick

This isn't solved in AG assistant v4.3.8.
May you assign someone to deal with this and then update AG assistant?
Thanks.

**Comment by Mizzick** [comment]
@lancelot-moon thx for reminder

**Comment by Mizzick** [comment]
@aalpatkina please update mentioned phrases in onesky

**Comment by lancelot-moon** [comment]
@aalpatkina 
@Mizzick 

Do I need to use line break in the back of "reputation"?
`This website has a good reputation`
`according to $1`
or
`This website has a good reputation according to $1`

Thanks.

**Comment by Mizzick** [comment]
@lancelot-moon  No, you don't have to. This was some layout weakness, that should be done with css improvements.
