### ISSUE TITLE
Adguard Assistant Not Showing

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardAssistant#263]
@JonoHaysom commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardForMac/issues/372)

Issue with the Adguard assistant not showing on certain websites.

Steps to reproduce
1. head to MacRumors.com (or apple.com)
2. the Adguard Assistant is now available (ads are being correctly blocked however)
3. head to other websites and its showing

Expected behaviour
Adguard Assistant should show

Actual behavior
Adguard assistant is not visible or able to be summoned

Your environment
Using Safari 12.0.2 and AdGuard 2.0.0.484 Nightly
basic filters are enabled. 

---

@JonoHaysom commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardForMac/issues/372#issuecomment-437789375)

Another option would be to have AdGuard show as a contextual menu item rather than a overlay button.

**Comment by JonoHaysom** [comment]
Thanks @ameshkov. linkedin.com also breaks it as another reference

**Comment by im3or** [comment]
@JonoHaysom please see if fanfox.net breaks it?

**Comment by im3or** [comment]
Assistant not showing at kissanime.ru also. Please check

**Comment by JonoHaysom** [comment]
@im3or it shows for me. however linked.com and MacRumors.com its not there.

a contextual menu would be perfect as it can be summoned anytime within the browser and there won't be the overlay of the assistant logo.

**Comment by tomiams** [comment]
I found that the assistant does not show up on multiple websites as well. Adding this rule to the user filter solved the issue:
@@||local.adguard.org^$important,document,~extension

It now shows up on MacRumors.com, linkedin.com, and everything else I tried.
Since www.apple.com was added to my https filter exclusion list, it did not show up there. When I removed www.apple.com from the https exclusion list, the assistant showed up just fine.

AdGuard for Mac Nightly 2.0.0.504 (CL-1.3.113)
Safari Technology Preview 12.2 Release 75
MacOS 10.14.3

**Comment by ameshkov** [comment]
Huh, that one is a tricky solution! What exact filters do you have enabled?

**Comment by tomiams** [comment]
All of them:
AdGuard Experimental
AdGuard Safari
NoCoin
Spam404
Malware Domains
I don't care about cookied
Adblock Warning Removal
Fanboy's annoyances
Adguard annoyances
Fanboy's social blocking
Adguard social media filter
Fanboy's anti-thirdparty fonts
Fanboy's anti-facebook
Fanboy's enhanced tracking
easyprivacy
Adguard tracking protection
peter lowe
easylist
Adguard base

As well as multiple custom ones. Let me know if they would be helpful to list.
Most of these filters are customized, however, to remove a lot of the exceptions. If there's a fast way to post a .txt of my filters combined, do let me know.

**Comment by ameshkov** [comment]
Well, what I am trying to figure is which filter has blocked AdGuard's `local.adguard.org`.

On the other hand, anyways, AG shouldn't block it as this is not a real domain and not a real remote request, so this is bug.

**Comment by tomiams** [comment]
I'll search for that. In the meantime, it might be helpful to note that whenever the assistant did not show up, Safari's console showed that loading local.adguard.com returned a 400 error.

**Comment by ameshkov** [comment]
Ah, that's another bug btw. Could you please update the AG nightly to the latest version, it should go away.

**Comment by tomiams** [comment]
Every mention of AdGuard in my lists. All, except the last two, were enabled:

Filter - All-in-One Customized Adblock List 2.4:
```
adguard.com##.gh-subscribe
adguard.com##.sticky-bar--cookie
@@||adguard.com/public/Adguard/Blog/Android/comparison/facebook_$image,domain=adguard.com
@@||adguard.com/public/Adguard/Blog/Android/comparison/facebook_$image,domain=adguard.com
adguard.com###floatingNavigation
```
Filter - AdGuard Base filter (everything that mentions adguard is enabled)

Filter - EasyList
```
@@||adguard.com/public/Adguard/Blog/Android/comparison/*_ads_$image,domain=adguard.com
@@||api.paymentwall.com^$domain=adguard.com
@@||pcwdld.com/wp-content/uploads/*/AdGuard.$domain=pcwdld.com
```
Filter - AdGuard Tracking Protection (everything that mentions adguard is enabled)

Filter - AdGuard Social Media (everything that mentions adguard is enabled)

Filter - Fanboy's Social Blocking
`@@||adguard.com/public/Adguard/Blog/Android/comparison/facebook_$image,domain=adguard.com
`
Filter - AdGuard Annoyances (everything that mentions adguard is enabled)

Filter - Fanboy's Annoyances
`@@||adguard.com/public/Adguard/Blog/Android/comparison/facebook_$image,domain=adguard.com
`
**Filter - AdGuard Safari (These coming two rules were disabled by me by mistake. They are now enabled)**
```
**@@safari-extension://com.adguard.safari-$document
@@safari-extension://com.adguard.safaridev-$document**
```

**Comment by tomiams** [comment]
> On the other hand, anyways, AG shouldn't block it as this is not a real domain and not a real remote request, so this is bug.

Well, looking at my AdGuardHome that's located on a raspberry pi I found multiple recent requests to `local.adguard.org` in the logs.

I'm unsure if this happened before but it is happening currently on AG 2.0.0.511 so apparently requests to local.adguard.org are leaving the mac.

**Comment by ameshkov** [comment]
It's okay, the browser tries to resolve it when it sees it. AdGuard does this as well, and then it intercepts requests to this domain's IP address and processes it locally.
