### ISSUE TITLE
Assistant icon not displayed

### ISSUE THREAD

**Issue by Elenve** [AdguardTeam/AdguardAssistant#265]
AdGuard Assistant icon does not appear here:
https://www.on-mag.fr/index.php/video-hd/news/home-cinema/18706-l-installation-a-v-de-la-semaine-video-multiroom-et-domotique-pour-un-gite-haut-de-gamme

Reinstalling does not help.

OS: Windows
User ID: 1152213

**Comment by ameshkov** [comment]
Disabled by a filter rule due to a bug. The exception rule will be removed later.

**Comment by Pierre7855** [comment]
When do you intend to solve the bug problem and remove the exception rule ?

**Comment by TheHasagi** [comment]
@Pierre7855 

AdGuard assistant already available on the website, do you still facing an issue with it?

**Comment by Pierre7855** [comment]
> @Pierre7855
> 
> AdGuard assistant already available on the website, do you still facing an issue with it?

Actually, adguard assistant is not showing. But according to ameshkov I have to wait until he removes the bug in order to remove the exception rule on this site.

**Comment by Pierre7855** [comment]
> Disabled by a filter rule due to a bug. The exception rule will be removed later.

Hello ameshkov,
about the site https://www.on-mag.fr/index.php/video-hd/news/home-cinema/18706-l-installation-a-v-de-la-semaine-video-multiroom-et-domotique-pour-un-gite-haut-de-gamme

From the 4 Dec, have you found the bug and could you remove the exception rule ?

**Comment by Pierre7855** [comment]
@ameshkov 
Hi,
as you have released adguard version 7, could you remove the exception rule on this site (actually adguard assistant does not appear) ?

**Comment by ameshkov** [comment]
@Pierre7855 hi Pierre!

I've just tested it and it seems okay, but it'd be better if you could also verify this.
Please open "Filter editor" -> find `@@||on-mag.fr/index.php^$elemhide,jsinject,extension` and disable this rule

Do you see any issues with the website?

**Comment by Pierre7855** [comment]
@ameshkov 
Hi Andrey !
I have found your exception rule into "english filter" and disabled it.
For me all is working well : I can see the adguard assistant, and the slide show at the bottom of the page is working well. 

So, you can disable this rule for all people using adguard !

**Comment by ameshkov** [comment]
Done, thank you!
