### ISSUE TITLE
Возможность отключить определённый фильтр для сайта, а не полностью фильтрацию на сайте

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardAssistant#269]
Хотелось бы иметь возможность на сайте отключить только определённый фильтр с помощью Ассистента AdGuard, а не только полностью фильтрацию на сайте. Это бы помогло при определении того, какой фильтр ломает сайт, или когда на сайте нужно, чтобы реклама была заблокирована, а иконка чата с поддержкой работала.

**Comment by akmLaVx** [comment]
@TheHasagi Please take a look at this request.

**Comment by akmLaVx** [comment]
Could anyone please take a look at this issue? @AdguardTeam/members

**Comment by ameshkov** [comment]
Технически реализовать отключение определенного фильтра для сайта будет ОЧЕНЬ сложно. Это просто не совместимо с текущим движком фильтрации.

Имеет смысл отключать правила по типу (например отключить косметические правила, или сетевые), это мы хотя бы реализовать сможем.

**Comment by Rakleed** [comment]
@ameshkov почему вы закрыли эту issue?
