### ISSUE TITLE
Integration mode not working in edge

### ISSUE THREAD

**Issue by InBlis** [AdguardTeam/AdguardAssistant#270]
Integration mode is not working in edge browser.
Adguard Version: 6.4.1814.4903
Windows 10 - 1809
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
![annotation 2018-12-29 060721](https://user-images.githubusercontent.com/23461491/50531453-29da0300-0b30-11e9-8ce3-b77448b1435d.jpg)

**Comment by ameshkov** [comment]
That's okay, it is disabled on Edge due to some browser limitation. The issue will go away once Edge switches to Chromium

**Comment by InBlis** [comment]
Thanks Andrey.
