### ISSUE TITLE
Некорректное заполнение поля "браузер" на сайте reports.adguard.com

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardAssistant#274]
Почему при жалобе на сайт через ассистента в браузере Google Chrome на сайте https://reports.adguard.com/new_issue.html на 3 шаге в поле "браузер" заполняется "Другой" вместо Chrome? Не могли бы вы сделать так, чтобы заполнялся Chrome, пожалуйста?

У меня Google Chrome 74.0.3729.157, AdGuard 6.4.1814.4903, Помощник AdGaurd 4.3.10, [cкрин-рекординг](https://youtu.be/Xq5HEaWdA6E).

**Comment by akmLaVx** [comment]
Перенесите, пожалуйста, Ваш запрос в репозиторий [https://github.com/AdguardTeam/ReportsWebApp/issues].

**Comment by Rakleed** [comment]
https://github.com/AdguardTeam/ReportsWebApp/issues/196
