### ISSUE TITLE
Автоустановка бета-версии

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardAssistant#276]
Мне почему-то автоматически установилась бета версия помощника. А при установке версии 4.2.7 и при нажатии "Переустановить", мне установилась бета версия 4.3.9. Исправьте, пожалуйста, эту проблему, ведь я нигде не соглашался на установку бета-версий.

**Comment by ameshkov** [comment]
Проверьте пожалуйста обновления юзерскриптов, все должно быть уже в норме.

Спасибо что обратили внимание!
