### ISSUE TITLE
An option for showing/hiding AG Assistant icon. Maybe add AG Assistant item to browser's context menu?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardAssistant#278]
@ameshkov 

1. An option for showing/hiding AG Assistant icon.
2. Maybe add AG Assistant item to **browser's context menu**?

**Comment by BlazDT** [comment]
2nd point also requested on our reddit page:
reddit.com/r/Adguard/comments/bh3xdv/adguard_please_consider_removing_clutter/

**Comment by gitguys** [comment]
Shocked this isn't already an option.

**Comment by ameshkov** [comment]
This assistant is going to be replaced with a native extension in the next version of AG:
https://adguard.com/en/adguard-assistant/overview.html

**Comment by lonniev** [comment]
I don't mind that AdGuard is monitoring the page - but I never wanted AdGuard to _add_ pollution to the page, especially in a region of the screen that Material Design sites like to use for their (+) widget.

I can't find a setting to keep the service active but not put a commercial for AdGuard on the page. ;-)

**Comment by ameshkov** [comment]
@lonniev that's why the old assistant is effectively deprecated. Instead of it we suggest people to use the assistant extension: https://adguard.com/en/adguard-assistant/overview.html#chrome
