### ISSUE TITLE
mcdonalds.fr - error 502 bad gateway

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardAssistant#283]
Assistant version 4.3.10 produces error 502 bad gateway when opening [https://www.mcdonalds.fr/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.mcdonalds.fr%2F)

Disabling Assistant and the site works.

To reproduce please disable this temp. rule in Base fliter:

@@||mcdonalds.fr^$extension

**Comment by GMib** [comment]
same with assistant disabled, what is base filter ? i removed mcdonalds line in user filter, don't work.
![ad](https://user-images.githubusercontent.com/31073459/56460089-4dee7800-639d-11e9-8d37-0deea41994cb.png)

**Comment by BlazDT** [comment]
For me it was enough to disable latest Assistant to make it work. Maybe some bug in AdGuard for Windows 6.4 which is fixed in latest nightly.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #878](https://github.com/AdguardTeam/CoreLibs/issues/878) via [**ZenHub**](https://www.zenhub.com/)
