### ISSUE TITLE
AdGuard Assistant doesn't work

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardAssistant#284]
AdGuard assistant doesn't work on all web pages, it is just non-clickable and the whole page is unavailable after you click on the assistant icon.

![img](https://uploads.adguard.com/TheHasagi3dmvf.jpg)

App version:

![img](https://uploads.adguard.com/TheHasagir6w57.jpg)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #894](https://github.com/AdguardTeam/CoreLibs/issues/894) via [**ZenHub**](https://www.zenhub.com/)
