### ISSUE TITLE
Adguard Assistant for Edge on Chromium?

### ISSUE THREAD

**Issue by cybergrimes** [AdguardTeam/AdguardAssistant#285]
Hey there, new beta of Adguard released ~3 days ago includes the new Edge on Chromium in the app list. Any plans to bring the Assistant in soon or is the plan to release when browser is on a stable channel?

thanks

**Comment by ameshkov** [comment]
Assistant is browser-agnostic, it will work in any browser that is filtered by AdGuard

**Comment by cybergrimes** [comment]
I guess I'm confused, I understand it will filter the browser but I'm asking about the hovering Adguard Assistant that I normally see in Firefox, Chrome or Opera. I don't have it in the new Chromium based Edge. 

I can post this on the forums if that's preferred...

**Comment by cybergrimes** [comment]
I posted because I wasn't seeing the Assistant function in new Edge. I thought it needed adding.
In case anyone else has this problem... I did a "Reset settings to default" in Adguard & that fixed it.
