### ISSUE TITLE
AdGuard Assistant not shown on sites in IE11

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardAssistant#286]
When opening the following sites in Internet Explorer 11 the Assistant is not shown, in Chrome it is shown:

https://www.naver.com
https://www.daum.net

Rules to the sites are applied though (tested with ##body).

When checking in console I see over 30 errors with:

This object does not support this property or method "includes". When clicking the location it points to local.adguard.com and this code snippet (I cannot find that code section in a filter rule though):

`return r},a=function(){return Date.now()-n};return{isIgnoredEventType:function(){return e.includes(s())&&a()<10}}}(),w=[],N`

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #901](https://github.com/AdguardTeam/CoreLibs/issues/901) via [**ZenHub**](https://www.zenhub.com/)
