### ISSUE TITLE
Перенесите иконку AdGuard Assistant на сайте squoosh.app/editor левее

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardAssistant#287]
На сайте [squoosh.app/editor](https://squoosh.app/editor) (чтобы зайти в редактор, нужно на [squoosh.app](https://squoosh.app) загрузить фото) иконка AdGuard Assistant мешает нажатию кнопки "Download", поэтому её стоит перенести левее.

<details><summary>Screenshot</summary>

![screenshot-squoosh app-2019 05 16-17-29-19](https://user-images.githubusercontent.com/19418601/57862251-bd228500-7800-11e9-8158-a7bb2ecc53c1.png)

</details>

**Comment by ameshkov** [comment]
Перетащить же можно вручную

**Comment by Rakleed** [comment]
@ameshkov я думал, что она закреплена. Спасибо.
