### ISSUE TITLE
Add a dark theme

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardAssistant#289]
Добавьте тёмную тему для интерфейса Помощника. И хотелось бы видеть функцию синхронизации темы с десктопным приложением или с браузером.

**Comment by BlagoYar** [comment]
Добавьте в настройку помощника в браузере тёмную со светлой тенью, чтобы не сливалось с тёмным фоном

**Comment by GauthierPLM** [comment]
Maybe this could be done with the CSS proper [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) to match the browser/system style.

**Comment by Rakleed** [comment]
@ameshkov почему вы закрыли эту issue?

**Comment by FadeMind** [comment]
@ameshkov any progress in? 
Regards
