### ISSUE TITLE
Element blocking doesn't work in firefox

### ISSUE THREAD

**Issue by freezewind** [AdguardTeam/AdguardAssistant#29]
I am Chinese, and sorry for my poor English.
Adguard for Windows v6.2.357 Beta
AdguardAssistant v4.0.4
window 7 64bit
Firefox v52.0.2
e10s is on
I have no green box in the Element blocking,and when I click the element I want to block, the Element blocking mode will be canceled.
ps. I have no problem with IE11

**Comment by ameshkov** [comment]
Hi! Thank you for reporting it!

There's the same issue with Chrome:
https://github.com/AdguardTeam/AdguardAssistant/issues/31

Let's close this one and continue discussion in #31
