### ISSUE TITLE
The Hide User-Agent field is not automatically flagged in the problem report form

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardAssistant#290]
В AdGaurd 7.0.2693.6661 RELEASE с Помощник AdGaurd 4.3.13 поле `Скрыть User-Agent` автоматически не помечается, хотя в настройках AdGuard у меня включена эта опция.

<details><summary>Screenshots:</summary>

![screenshot-reports-adguard-com-ru-new_issue-html-1559699010348](https://user-images.githubusercontent.com/19418601/58924434-7b746280-874c-11e9-809a-089fc64ef3ef.png)

![image](https://user-images.githubusercontent.com/19418601/58924448-87f8bb00-874c-11e9-9010-04f554286d78.png)

</details>

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #2732](https://github.com/AdguardTeam/AdguardForWindows/issues/2732) via [**ZenHub**](https://www.zenhub.com/)
