### ISSUE TITLE
Change Assistant color if the website is NOT blocked

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardAssistant#295]
As requested by user 461686,

> With the older version of AdGuard when we exclude a site from
> filtering with Adguard Assistant the entry was like this:
> @@||www.netflix.com$document With this version, the entry is like
> this: @@||www.netflix.com^$important,document,~extension With the old
> format we don’t see the assistant icon any more and we were aware
> that the site is not being filtered by AdGuard. But with the new
> filter, even if the site wasn’t being filtered, we do see the
> assistant icon. This makes hard to distinguish whether the site is
> being filtered or not. To modify the filtering status with the
> assistant is now easy, but it would be useful if the icon tıurns red
> if the site isn’t being filtered.

**Comment by zzebrum** [comment]
#254
