### ISSUE TITLE
Adguard Assistant Extension icon stuck to cursor

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#30]
Version 6.2.357.1887
Chrome 59.0.3071.36 (Official Build) beta (64-bit)

If you (intentionally or otherwise) drag the Adguard Assistant icon behind the taskbar and release it there, it'll then be stuck to your cursor and you (seemingly) can't un-stuck it short of closing Adguard or the browser window.

Double clicking on a valid space in the browser window sometimes seems to "let go" of it, but not always.

It doesn't carry over to other windows, but follows the cursor around as long as the browser is in focus.

Suggest that it automatically anchors itself to just above the taskbar if possible.

**Comment by 4-life** [comment]
Solved by #48
