### ISSUE TITLE
Assistant windows size

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/AdguardAssistant#300]
The manual blocking tool window started to appear smaller after the update 2.1.2.
<details><summary>Screenshot:</summary>

![IMG_6025](https://user-images.githubusercontent.com/34379403/62828050-add78b80-bbe5-11e9-899d-786d775ebb1e.jpg)

</details>

 But on some sites the window is larger.

<details><summary>Screenshot:</summary>

![IMG_6013](https://user-images.githubusercontent.com/34379403/62828048-a87a4100-bbe5-11e9-8c4b-b539d2163c15.jpg)

</details>

---

AdGuard Pro 2.1.2
iOS 12.4
5s 16 GB

**Comment by PentagramTr** [comment]
Other bug
A version number appears at the bottom right of the assistant window.

<details><summary>Screenshot:</summary>

![IMG_6104](https://user-images.githubusercontent.com/34379403/63598217-ce311e00-c5c7-11e9-90e0-9198760831b8.jpg)

</details>


AdGuard Pro 2.1.2
iOS 12.4
5s 16 GB

**Comment by ameshkov** [comment]
> AdGuard Pro 2.1.2

Well, AG Pro is quite old, and it'll be quite some time till it is on part with 3.0 in terms of Safari Content Blocking.

@timirila1 please check if this is an issue in the latest Assistant version.

**Comment by timirila1** [comment]
@ameshkov 
We use `vh` and `vw` units in our markup that's why Assistant may looks different from site to site.

**Comment by ameshkov** [comment]
@timirila1 can we resolve it somehow?

**Comment by timirila1** [comment]
@ameshkov let me check if we can do something with it. I put it on our backlog for a while.
