### ISSUE TITLE
Adguard Assistant – 'Block ad on this website' not working

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#31]
Version 6.2.357.1887
Chrome 59.0.3071.36 (Official Build) beta (64-bit)

After selecting [Block ad on this website](http://i.imgur.com/TizEcg2.png), it doesn't actually let me select an element. The regular green outline for selecting an element does not show up and [clicking on the page interacts with it as normal](https://gfycat.com/SparklingGleefulAsianpiedstarling), dismissing the element selection pop-up.

Element blocking through the browser extension works fine.

**Comment by ameshkov** [comment]
@fazlee712 just on github?

**Comment by fazlee712** [comment]
@ameshkov I experience this behaviour on all websites.

**Comment by ameshkov** [comment]
Cannot reproduce it on my side. What browser extensions do you have installed?

**Comment by fazlee712** [comment]
AdGuard Adblocker 2.5.11
Enhanced Steam 9.3
Join 1.5.15
Lastpass 4.1.45
Moonlight 0.7.1
Reddit Enhancement Suite 5.6.1

I don't know if it's worth noting that this feature is functional on Adguard Windows 6.1 with everything else kept the same.

**Comment by ameshkov** [comment]
What's assistant version (you can check it in ag -> settings -> extensions -> help icon)?

**Comment by fazlee712** [comment]
<img width="314" alt="adguard_2017-05-10_08-17-46" src="https://cloud.githubusercontent.com/assets/10059800/25875119/306ea0ee-3559-11e7-9c73-fc4504b9cfa8.png">

**Comment by ameshkov** [comment]
@fazlee712 does it help to reinstall it?

**Comment by fazlee712** [comment]
@ameshkov reinstalling the extension, or even reinstalling Adguard 6.2 entirely, does not seem to resolve the issue

this is on Windows 10 build 16188.1000 if it's of any relevance

**Comment by ameshkov** [comment]
@freezewind reported the very same issue with FF

**Comment by ameshkov** [comment]
The problem is that I don't yet understand what's going on and how to reproduce it:)

**Comment by ameshkov** [comment]
@fazlee712 could you please inspect browser console? Anything suspicious there?

**Comment by fazlee712** [comment]
No big deal; the Adguard browser extension can still perform the function just fine – in fact I prefer the browser extension's context menu as opposed to the 'permanent' icon from the desktop client. I don't suppose it would be possible to modify the browser's context menu solely from the desktop client (and have an option to toggle between that and the AG icon)?

I was just looking to minimize the number of browser extensions installed so I was hoping to just use the desktop client's built-in feature :)

**Comment by fazlee712** [comment]
<img width="1080" alt="2017-05-10_08-43-12" src="https://cloud.githubusercontent.com/assets/10059800/25875792/baaacd70-355c-11e7-8247-0e644583a1fb.png">

**Comment by ameshkov** [comment]
> don't suppose it would be possible to modify the browser's context menu solely from the desktop client (and have an option to toggle between that and the AG icon)?

Yeah, that's why assistant is executed in a page context -- in order to make it cross-browser.

Anyways, the issue seems to really weird and I guess we need it to be fixed by the time of release.

**Comment by ameshkov** [comment]
@fazlee712 could you please scroll the DOM-tree window to the bottom and take a screenshot? There should be `sg_border` elements (which actually are selection borders)

**Comment by ameshkov** [comment]
DOM-tree window is right under the "Elements" item.

**Comment by fazlee712** [comment]
<img width="1080" alt="chrome_2017-05-10_08-51-05" src="https://cloud.githubusercontent.com/assets/10059800/25875994/e4db0212-355d-11e7-951e-85920f850d5d.png">

**Comment by ameshkov** [comment]
Huh, seems okay.

Do you see how those elements style changes when you hover the mouse cursor over page elements?

**Comment by fazlee712** [comment]
https://gfycat.com/ShadyWealthyHydra

**Comment by ameshkov** [comment]
It looks as if AG script was not receiving mouse position events.

Thank you for your help! We'll try reproducing it with the same extensions as you have (as I've no other idea what could be messing with it:))

**Comment by ameshkov** [comment]
@vozersky please assist

**Comment by vozersky** [comment]
I've installed those 4 extensions (plus Adguard extension), but still can't rep, unfortunately.

@fazlee712 Could you please temporarily disable them in your browser and check if it actually helps? I would really appreciate that

**Comment by fazlee712** [comment]
@vozersky 

ok I disabled all browser extensions (including Adguard browser extension) and it still exhibits the same behavior. Also tried disabling all other userscripts in Adguard (even though none of them are global – only affecting specific domains) and same thing.

**Comment by freezewind** [comment]
@vozersky 
I also have a same issue with firefox and it still happan when I created a new profile.

**Comment by vozersky** [comment]
@fazlee712 do you still experience this issue? what about other browsers? 

@freezewind what extensions do you have in FF? please try disabling them. Any other apps\scripts that can distort the page layout?

**Comment by fazlee712** [comment]
@vozersky seems to work fine on Edge 41.16193.1001.0

still happening on Chrome 59.0.3071.47

**Comment by freezewind** [comment]
@vozersky 
I use a "new profile" to test, so my FF is default setting and no extensions.
IE 11 work fine
window 7 64bit
Firefox v52.0.2
e10s is on

**Comment by rayman3003** [comment]
I think (if its possible) merge the two issues in one topic. I continue here.
I tried with so many browsers & the results:

**NOT WORKING** browser -> Firefox - Chrome - Maxthon (& Maxthon Nitro) - Opera (new one with chrome engine) - Apple Safari (In this one the Assistant completely not appears (only the icon can be seen but not clickable))

**WORKING** browsers -> IE - EDGE - Opera 12 (old one) - Avant Browser (IE Engine)

**Comment by freezewind** [comment]
Any news?

**Comment by vozersky** [comment]
@freezewind try the latest build: https://AdguardTeam.github.io/AdguardAssistant/assistant.user.js

**Comment by freezewind** [comment]
@freezewind
I find out the problem is the Private Build Firefox.
The Official Build is okay.
I use this firefox and the new Assistant doesn't work with it.
https://sourceforge.net/projects/lawlietfox/files/Release/53.x/lawlietfox-53.0.2-1-win32-vc14-betterpgo-sse2.7z/download
Is it the bug from the Private Build Firefox or the new Assistant?

**Comment by vozersky** [comment]
@fazlee712 have you actually tried Assistant 4.0.9 mentioned above? Any changes? 
I've installed both custom browsers you've linked and selecting element works fine for me.

**Comment by freezewind** [comment]
@vozersky I tried the 4.0.9, but nothing is changed.
![adgais](https://user-images.githubusercontent.com/3954389/28067987-816ae136-65f8-11e7-8b39-dbd7fb46cd14.gif)

**Comment by freezewind** [comment]
@vozersky I download three different versions of firefox from here. 
https://sourceforge.net/projects/lawlietfox/files/Release/
52.x and 53.x doesn't work, but 54.x is okay.
![adgais2](https://user-images.githubusercontent.com/3954389/28070238-1003c950-6601-11e7-91bb-7e02b8780b7c.gif)

**Comment by vozersky** [comment]
@freezewind  it's good that 54.x works for you now. Anyway, I am pretty sure all issues with this private builds are not related to Assistant. Still worked for me though.
