### ISSUE TITLE
"Filtering on this website" is disabled for domains in user rules

### ISSUE THREAD

**Issue by crankygeologist** [AdguardTeam/AdguardAssistant#316]
Is there a known issue with the "slider" being in the red/disabled position on pages that match domains in the user rules filter? The slider is shown in the red or disabled position, but the filters seem to be working. Unfortunately, I cannot consistently reproduce the issue.

**Comment by ameshkov** [comment]
Nope, not known. Could you please tell me what exact rules are triggering this?

**Comment by crankygeologist** [comment]
Thanks for the quick reply. It seems to be working now after rebooting my computer, but the rules and domains having this issue are:

`csmonitor.com###content-recommendation
csmonitor.com###csm-header-content > div.collapse.row > div.visible-scroll-top:first-child > div.float-right:nth-child(2) > ul.tools-menu > li.show-for-large.text:nth-child(2)
csmonitor.com###csm-header-content > div.collapse.row > div.visible-scroll-top:first-child > div.float-right:nth-child(2) > ul.tools-menu > li.show-for-large.text:nth-child(2)
csmonitor.com###csm-page-bound > div.ezf-default-r18:nth-child(5) > div.eza-page:nth-child(2) > div.row.small-collapse:last-child > div.columns.small-12.medium-12.end.large-4.ezz-right:last-child > div.row > div.columns.small-12
csmonitor.com###csm-page-bound > div.ezf-default-r18:nth-child(5) > div.eza-page:nth-child(2) > div.row.small-collapse:last-child > div.columns.small-12.medium-12.large-8:first-child > div.row > div.columns.small-12.ezz-middle_top:first-child
csmonitor.com###full-audio-block
csmonitor.com###right-column
csmonitor.com###story-content > div.row.with-story-body-toggle:last-child > section.large-10.large-offset-1.small-centered.float-left.paywall-position-rel.columns > div.row:nth-child(4) > div.small-centered.small-12.columns > div.story-two.eza-body.small-11.small-centered.medium-10.large-12.deep-read.story-body-toggle-content.prem.default:last-child > div.injection:nth-child(25)
csmonitor.com###story-content > div.row.with-story-body-toggle:last-child > section.large-10.large-offset-1.small-centered.float-left.paywall-position-rel.columns > div.row:nth-child(4) > div.small-centered.small-12.columns > div.story-two.eza-body.small-11.small-centered.medium-10.large-12.deep-read.story-body-toggle-content.prem.default:last-child > div.injection:nth-child(32)
csmonitor.com###story-content > div.row:last-child > section.large-10.large-offset-1.small-centered.float-left.paywall-position-rel.columns > div.row:nth-child(3) > div.small-centered.small-12.columns > div.story-two.eza-body.small-11.small-centered.medium-10.large-12.deep-read.story-body-toggle-content.prem.default > div.injection:nth-child(16)
daringfireball.net##DIV[id="SidebarMartini"]
theatlantic.com###article-section-1 > div.u-dynamic-content.js-dynamic-content.is-rendered.lazyloaded:nth-child(4)
theatlantic.com###article-section-1 > figure:nth-child(6)
theatlantic.com###article-section-1 > h3:nth-child(5)
theatlantic.com###article-section-4 > div.js-dynamic-content.is-rendered.lazyloaded:nth-child(4) > section.c-related-video
theatlantic.com###article-video
theatlantic.com###housepromo-d
theatlantic.com###injected-recirculation-link-0
theatlantic.com###injected-recirculation-link-1
theatlantic.com###injected-recirculation-link-2
theatlantic.com###injected-recirculation-link-3
theatlantic.com###leaflets > section.c-leaflets > div.c-leaflets__container
theatlantic.com###main-article > div.l-article__container.js-article-container:last-child > div.blah:nth-child(3) > aside.l-rail.l-rail--right.l-rail--2:last-child > div.u-dynamic-content.js-dynamic-content.is-rendered.lazyloaded
theatlantic.com###main-article > div.l-article__container:last-child > div.blah:first-child > aside.l-rail.l-rail--right.l-rail--1:last-child
theatlantic.com###main-content > div.l-article-recirc:nth-child(2) > div.l-article-recirc__leaflet.u-dynamic-content.is-rendered.lazyloaded:last-child > section.c-leaflets
theatlantic.com###main-content > div.l-article-recirc:nth-child(2) > section.l-article-recirc__rivers:nth-child(2)
theatlantic.com###most-popular
theatlantic.com###share-social > ul.c-share-social__list
www.theatlantic.com##ASIDE[class="callout subscribe"]
www.theatlantic.com##ASIDE[class="callout"]
www.theatlantic.com##DIV[class="blocker-msg"]
www.theatlantic.com##DIV[class="module module-related related-categorization video"]
www.theatlantic.com##DIV[class="most-popular-header"]
www.theatlantic.com##DIV[class="most-popular-list"]
www.theatlantic.com##DIV[class="right-rail"]
www.theatlantic.com##DIV[id="article-comments"]
www.theatlantic.com##DIV[id="blocker-msg-start"][class="blocker-msg blocker-msg--active"]
www.theatlantic.com##SECTION[class="circ-promo"]
www.theatlantic.com##SECTION[class="follow toggleable"]
www.theatlantic.com##SECTION[class="newsletters toggleable"]
www.theatlantic.com##SECTION[class="subscribe"]
www.theatlantic.com##SECTION[id="toc-back-issues"][class="back-issues"]`

**Comment by ameshkov** [comment]
Well, looks more like a temporary glitch.

Anyways, we're going to replace Assistant with a browser extension in the next update, it should work more consistently.
