### ISSUE TITLE
Assistant missing on some sites in IE

### ISSUE THREAD

**Issue by northis** [AdguardTeam/AdguardAssistant#317]
**OK**
yandex.ru
adguard.org
**Not OK**
google.com
lenta.ru

with error in browser console
```
SCRIPT5009: 'Promise' is undefined
```

**Comment by maximtop** [comment]
Also in IE 11, I saw an error with AdGuard Extra
![image](https://user-images.githubusercontent.com/17272769/70506793-2de21380-1b3c-11ea-9d31-574eb00162ca.png)

**Comment by ameshkov** [comment]
It should not work in IE at all
