### ISSUE TITLE
Scrollbar sometimes become black on chromium-based browsers

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardAssistant#318]
@skipik commented on [Thu Dec 12 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3122)

### Steps to reproduce

1. Install Opera or Vivaldi
2. Use mouse gestures, open and clouse tabs with those gestures
3. Look at the scrollbar
4.

### Expected behavior

Scrollbar will be always normal
### Actual behavior

Scrollbar sometimes become black

<details><summary>Screenshot:</summary>

![cfb74b8576034ecc544e34fea7120fac](https://user-images.githubusercontent.com/24621645/70713146-6a596f00-1cf6-11ea-81d8-a5631ac34806.png)

</details>

### Your environment

* Environment name and version: Opera, Vivaldi, AdGuard (Stable, Beta or Nightly)
* Operating system and version: Microsoft Windows 10 Enterprise (x64) Build 18363.535 (1909/November 2019 Update)

---

@skipik commented on [Fri Dec 13 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3122#issuecomment-564993778)

Сейчас опишу более подробно: я долго не мог понять, почему возникает такой эффект. В итоге пришлось проверять весь софт, включая браузеры. Эксперименты показали, что виноват именно AdGuard, я удалил его и использовал uBlock Origin в течение 2 недель - баг со скроллбаром не проявился.
Воспроизводится не каждый раз, но часто, нужно открывать и закрывать страницы мышиными жестами и в опр. момент возвращаемся на пред страницу с таким чёрным скроллбаром. СтОит чуть прокрутить колёсико и он вновь становится нормальным. Раздражает ужасно.
Готов предоставить любые логи и очень надеюсь, что будет исправлено.

---

@skipik commented on [Thu Dec 12 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3122#issuecomment-564997962)

В идеале - нужно ставить Opera или Vivaldi и использовать их хотя бы 1-2 дня, открывая и закрывая вкладки мышиными жестами, в какой-то момент баг проявится.

---

@ameshkov commented on [Sun Dec 15 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3122#issuecomment-565844514)

А если в AdGuard отключить помощника просто -- будет воспроизводиться?

---

@skipik commented on [Mon Dec 16 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3122#issuecomment-565851310)

@ameshkov спасибо, что откликнулись. Я попробую без помощника и отпишу информацию здесь.

---

@skipik commented on [Mon Dec 16 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3122#issuecomment-566122544)

@ameshkov вы оказались правы, с отключённым помощником не воспроизводится. Этому багу уже несколько месяцев, я просто никак не мог понять причину и грешил на браузер. Только детальное исследование всего софта помогло понять истинную причину - AdGuard. Надеюсь, что это удастся поправить.

**Comment by skipik** [comment]
Ребят, возможно, что AdGuard не причём здесь. Я сейчас детально всё тестирую. Дайте мне немного времени. Ещё отпишусь.

**Comment by skipik** [comment]
Похоже, что проблема решилась и AdGuard был не виноват.
Просьба закрыть инц до воспроизведения.

**Comment by skipik** [comment]
Проблема опять появилась, но воспроизводится крайне сложно и редко.
Возможно, что поможет глобальная переделка помощника, о которой упоминал @ameshkov .

**Comment by zzebrum** [comment]
@skipik да вроде уже будет первая бета AdGuard for windows
