### ISSUE TITLE
Adguard Assistant does not respect some elements on the page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#32]
Go to https://vk.com/your_id_here (you have to sign up on the site) and look at this:

http://jpegshare.net/ba/a5/baa58fb8ce1715dcb68664719b9868e3.png.html

And now I'm trying to show you how it was before those assistant changes:

http://jpegshare.net/93/07/9307382f4550158bc6d1c617b31b7c4f.png.html

I know that I can move it, but I'm happy with its default position. So I just want so see both elements correctly.

Adguard 6.2.357.1887, Opera Developer 46.0.2573.0.

**Comment by ameshkov** [comment]
@skipik in prev assistant version we handled VK and Facebook cases and changed default bottom-right position there so that it didn't mess with the other elements. I guess it makes sense to do the very same thing in the new version.

**Comment by skipik** [comment]
@ameshkov Yeah, I liked the way how it was before. Aguard assistant was always in its default position and that VK element (with the numbers of online users) was exactly above it.

**Comment by ameshkov** [comment]
@4-life does not work in the latest dev build
