### ISSUE TITLE
Assistant giving 'DISABLED' error

### ISSUE THREAD

**Issue by Greigh** [AdguardTeam/AdguardAssistant#331]
AdGuard is not working at all when searching the web with the Browser Assistant. I have the AdGuard for Mac installed. All up to date AdGuard for Mac is on v2.4.8.797 release (CL-1.5.269) and my AdGuard Browser Assistant extension is on v1.0.10. It does produce errors within my browser when I turn on Developer Mode: "TypeError: Cannot read property 'DISABLED' of undefined" and "Uncaught (in promise) TypeError: Cannot read property 'DISABLED' of undefined".

I have installed the Legacy Extension for the time being and that works fine.

I would like to note that it "works" fine when in a New Tab but when I make a search on Google or browse the web it produces this error.

if you want anymore info about the errors about, please let me know :) Thanks for all your hard work.

https://user-images.githubusercontent.com/57759540/85904509-ea4caf80-b7d6-11ea-822a-c798a534874d.png

https://user-images.githubusercontent.com/57759540/85904247-32b79d80-b7d6-11ea-8c07-6afd2a4fab3e.png

**Comment by zzebrum** [comment]
@Greigh can not reproduce on my side. Have you tried to reinstall the Assistant?

**Comment by Greigh** [comment]
@zzebrum Multiple times. I just tried it again with no luck. 

I am using it with the Brave Browser (Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)) so maybe that's why you can't reproduce it?

When webpages are loading the Assistant says "AdGuard is Loading". Not sure if that helps at all.

**Comment by Greigh** [comment]
I can confirm it is a Brave Browser (possibly only macOS) only bug as it works fine in Chrome and Firefox. Even a fresh restore of both AdGuard and Brave browser do not fix this this issue.

**Comment by maximtop** [comment]
Issue moved to [AdguardTeam/BrowserAssistant #26](https://github.com/AdguardTeam/BrowserAssistant/issues/26) via [**ZenHub**](https://www.zenhub.com/)
