### ISSUE TITLE
Пожелания по новому Помощнику

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardAssistant#332]
@Vitalik93 commented on [Sat May 30 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3345)

Думаю у нового Помощника стоит поменять иконку - убрать с неё букву "А", все равно её на панели почти не видно. Вместо этого можно добавить отображение на иконке количества заблокированных элементов, по аналогии с браузерным расширением, а также добавить в само расширение статистику - сколько заблокировано для текущего сайта и общее количество блокированных запросов. В случае же с Firefox - всё же нужно перенести Помощник в магазин расширений и чтобы ссылка из программы на его установку вела как раз в магазин расширений.
![Аннотация 2020-05-30 222221](https://user-images.githubusercontent.com/34383288/83338520-8ad9ad80-a2c5-11ea-82c6-0c1e343b35d1.png)
![Аннотация 2020-05-30 222332](https://user-images.githubusercontent.com/34383288/83338523-8e6d3480-a2c5-11ea-8070-9829c6643306.png)

**Comment by maximtop** [comment]
Issue moved to [AdguardTeam/BrowserAssistant #25](https://github.com/AdguardTeam/BrowserAssistant/issues/25) via [**ZenHub**](https://www.zenhub.com/)
