### ISSUE TITLE
FR: Reduce the number of clicks required to block an element

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdguardAssistant#334]
Example: Popup of `element blocking` even after selecting `block an element on this page`

**Comment by specter78** [comment]
@ameshkov Warning popup saying `content blocker is disabled` is very annoying and should be shown only **once** and not every time assistant is launched. 

Even if the blockers are disabled, `user filters` list still works.

**Comment by ameshkov** [comment]
Hm, could you please show it on a screenshot? I don't understand what popup you are referring to

**Comment by specter78** [comment]
> Hm, could you please show it on a screenshot? I don't understand what popup you are referring to

<details>
<summary>Screenshot</summary>

![popup](https://user-images.githubusercontent.com/40606342/88931918-0d1d2880-d29b-11ea-8a32-29f228a02722.jpg)

</details>

**Comment by zzebrum** [comment]
@specter78 user rules are working if at least one content blocker enabled. But yes, in this case, we should show the notification only if all content blockers disabled.

**Comment by specter78** [comment]
> Even if the blockers are disabled, `user filters` list still works.

@zzebrum A little clarification - I have filters enabled in safari settings, but not within adguard app.

**Comment by zzebrum** [comment]
now, I'm a little confused :) in Safari settings you mean content blockers, right?

**Comment by specter78** [comment]
> in Safari settings you mean content blockers, right?

Yes. Sorry, my bad.

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdguardForiOS #1611](https://github.com/AdguardTeam/AdguardForiOS/issues/1611) via [**ZenHub**](https://www.zenhub.com/)
