### ISSUE TITLE
Only inject legacy Assistant to browsers not already using extension-based Assistant

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardAssistant#339]
This feature request has been processed in helpdesk ticket 2958771.

As it stands now, the legacy Assistant injects itself into all browsers it can find. If said browser is already using an extension-based Assistant, legacy Assistant should have a way of detecting it and not injecting itself there.

App logs, if required, can be found attached to helpdesk ticket.

**Comment by ameshkov** [comment]
Most likely, we'll get rid of the old Assistant eventually.
