### ISSUE TITLE
 UI Turned grey

### ISSUE THREAD

**Issue by Sun0613** [AdguardTeam/AdguardAssistant#346]
Safari 11.1.2       AdguardAssistant 4.3.40

<img width="329" alt="屏幕快照 2021-01-09 上午9 28 01" src="https://user-images.githubusercontent.com/46019412/104079475-47cdb880-525e-11eb-9aca-1ca89c2b4ae0.png">

<img width="403" alt="屏幕快照 2021-01-09 上午9 38 43" src="https://user-images.githubusercontent.com/46019412/104079514-7ea3ce80-525e-11eb-8860-0d60b2648cf8.png">

**Comment by ameshkov** [comment]
@Sun0613 do you have dark theme enabled on MacOS?

**Comment by Sun0613** [comment]
No dark theme.
But version 4.3.37 is no problem.
