### ISSUE TITLE
Github name while reporting

### ISSUE THREAD

**Issue by BALTAGY** [AdguardTeam/AdguardAssistant#347]
Hi,

While reporting a site and type my Github username, it don't mention my username it just show as a text like this report

https://github.com/AdguardTeam/AdguardFilters/issues/71893#issuecomment-775440834

It should mention my username BALTAGY as before but now i have to bookmark what i report since it don't show as mention

from Adguard support email it's kinda related to this 
https://github.com/AdguardTeam/ReportsWebApp/issues/255

Before i used to see all reports that i did by selecting "Everything Mentioning you" so i can see a list of my reports and what is still open and what is closed

Now it's empty, i have to check every report manually !

![Snap1](https://user-images.githubusercontent.com/33364352/107521909-c4381c00-6bbb-11eb-8433-82124e33202f.jpg)

When i used Legacy Assistant i never had this problem and i could even click on my name and see all reports in one page like this pic

![Snap2](https://user-images.githubusercontent.com/33364352/107521946-d0bc7480-6bbb-11eb-9f54-474bebfd8856.jpg)

Before:
![Snap3](https://user-images.githubusercontent.com/33364352/107521985-dca83680-6bbb-11eb-8a0a-1b2e20ad04eb.jpg)

After:
![Snap4](https://user-images.githubusercontent.com/33364352/107522010-e3cf4480-6bbb-11eb-80ce-73448e948afa.jpg)

Thanks
@BALTAGY

**Comment by slavaleleka** [comment]
there are users which does not have GitHub account and enters random name, and then wrong user summoned to the issue. that's why we had to change that

to trace the issues you reported you should [subscribe for updates](https://uploads.adguard.com/slbdzdr86np0.png)

**Comment by BALTAGY** [comment]
@slavaleleka Can't be changed that i have to login to mention my self to the report ?

Using my account make it easy to track all reports in one page

**Comment by slavaleleka** [comment]
Issue moved to [AdguardTeam/ReportsWebApp #262](https://github.com/AdguardTeam/ReportsWebApp/issues/262) via [**ZenHub**](https://www.zenhub.com/)
