### ISSUE TITLE
Increasing the contrast the "X" button on the dark theme

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/AdguardAssistant#363]
@Oleg-Chashko commented on [Mon Nov 22 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1897)

<img width="668" alt="Screen Shot 2021-11-22 at 18 47 53" src="https://user-images.githubusercontent.com/62497891/142920093-288b118a-5c12-486a-b9d8-c58f655f8af9.png">

**Comment by Versty** [comment]
Implemented successfully
