### ISSUE TITLE
Refresh Page Button In Filtering Log of Assistant Menu

### ISSUE THREAD

**Issue by bkrucarci** [AdguardTeam/AdguardAssistant#365]
### Feature Request

**OS:** Windows 10 Latest
**Adguard Windows :** Latest
**Browser :** Opera Latest
I have the latest Opera Assistant insalled from [here](https://chrome.google.com/webstore/detail/adguard-browser-assistant/fbohpolgemkbfphodcfgnpjcmedcjhpn)

I feel the need of **"refresh & reload the page"** function in Filtering log of new assistant. Thank you

![Screenshot_1](https://user-images.githubusercontent.com/15933805/145731624-324db6c0-1238-4287-99b9-9be9c3828530.png)

**Comment by zzebrum** [comment]
@bkrucarci please check it in the latest beta version: https://chrome.google.com/webstore/detail/adguard-adblocker-beta/gfggjaccafhcbfogfkogggoepomehbjl
