### ISSUE TITLE
Assistant not detecting AdGuard installation

### ISSUE THREAD

**Issue by FauconSpartiate** [AdguardTeam/AdguardAssistant#367]
AdGuard assistant doesn't detect any AdGuard installation, even though it is on default settings. I tried messing around with some settings, but nothing changed.

![image](https://user-images.githubusercontent.com/49079695/147391007-c00c8903-809f-4793-8b2c-80a033389d63.png)

- Latest Windows 10 build
- AdGuard Windows stable / beta / nightly

**Comment by Aydinv13** [comment]
What browser do you use? Which version of AdGuard&Browser assistant is it?

**Comment by zzebrum** [comment]
@FauconSpartiate any news?

**Comment by FauconSpartiate** [comment]
@Aydinv13 
Latest stable Chrome build, and latest release Adguard version

**Comment by FauconSpartiate** [comment]
@zzebrum 
Nope, it has been ongoing since I first installed it, and is still broken...

**Comment by Aydinv13** [comment]
@FauconSpartiate have you tried to reinstall Browser Assistant?
- Remove Assistant from Chrome
- Go to AdGuard's settings-> Browser Assistant
- Click on `Get the extension` (previously, you need to set Chrome as your default browser)

**Comment by FauconSpartiate** [comment]
Yep, reinstalled the extension, Adguard, and even chrome, but still the same...

**Comment by ameshkov** [comment]
Is it normal Chrome installation or something like a portable version?

**Comment by maximtop** [comment]
Issue moved to [AdguardTeam/BrowserAssistant #58](https://github.com/AdguardTeam/BrowserAssistant/issues/58) via [**ZenHub**](https://www.zenhub.com/)
