### ISSUE TITLE
What's the deal with "legacy" Assistant Vs 1.2x Assistant?

### ISSUE THREAD

**Issue by J-HS-L** [AdguardTeam/AdguardAssistant#369]
I'm confused, were told to use the browser-specific adguard assistant, not this one, unless our browser isn't supported, whereupon we use this. But I thought this was being phased out and only the browser specific one was being actively developed? Yet, this seems to be more actively developed than the browser-specific one!?! at least for edge (chrome)

**Comment by ameshkov** [comment]
This repo also contains the "library" code that is used among other AdGuard products, the one that is responsible for rendering the in-page "select an element" dialog window. So even when the legacy userscript is fully phased out, the repo will still be active.
