### ISSUE TITLE
The new Assistant settings window is located quite away from the icon

### ISSUE THREAD

**Issue by OlegSUP** [AdguardTeam/AdguardAssistant#37]
![image](https://cloud.githubusercontent.com/assets/26434103/25898200/b95d8840-3593-11e7-8e16-b9fed56a917f.png)

![image](https://cloud.githubusercontent.com/assets/26434103/25898239/e4b6891a-3593-11e7-89f5-07b5e5ef2eea.png)

The settings popover is too large

Reported here: 1479416

**Comment by ameshkov** [comment]
Won't fix, that's by design
