### ISSUE TITLE
AdGuard for Windows app window doesn't open from the assistant

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardAssistant#374]
It's fine when you open settings and filtering log for the first time. Also there's no problem if you open second time filtering log and settings with context menu(cursor right menu) but AdGuard icon flashes in taskbar(if you open second time). But when you try to open it again, the window appears and suddenly disappears. Then AdGuard icon flashes in taskbar.

https://user-images.githubusercontent.com/35523759/162980456-6da25ca1-e2c7-44a7-92a3-68ae5464c0c3.mp4

**Comment by Aydinv13** [comment]
In fact the app window opens but in the background. Will be fixed in the Windows repository
