### ISSUE TITLE
Report the website broken and icon missing

### ISSUE THREAD

**Issue by Bushido1** [AdguardTeam/AdguardAssistant#38]
I use the latest Beta and when I click ,,Report the website" in Assistant, then the Assistant window closes, not redirecting to the box where I can insert a comment about the website.
Also, the option to take back the latest filter rule is gone. Now I have to open Adguard for Windows in order to do it.

**Comment by ameshkov** [comment]
That's just a temporary solution, we'll fix it once the reporting website is up.
