### ISSUE TITLE
Icon vanish after some time

### ISSUE THREAD

**Issue by xu-minghao317** [AdguardTeam/AdguardAssistant#380]
Describe the bug
The extension icon is not showing anymore shortly after installation.

To Reproduce
```shell
brew install adguard --cask
```
- Reboot computer

Screenshots

Not showing in the menu bar
<img width="264" alt="Screen Shot 2022-08-12 at 1 16 39" src="https://user-images.githubusercontent.com/85087583/184180848-14231e6b-7678-4cb4-a231-0d3234f79942.png">

But enabled already
<img width="217" alt="Screen Shot 2022-08-12 at 1 17 05" src="https://user-images.githubusercontent.com/85087583/184180883-9aa35113-96f1-406a-8460-776e4353ff77.png">

Additional
I reinstalled adguard, it fix the problem for some time but it vanished again.
Any ideas why this will happen?

OS: macOS 12.5
Browser safari
Version 15.6

**Comment by ameshkov** [comment]
As I understand, Safari shows only a limited number of extension icons, and the order is not set in stone.

**Comment by xu-minghao317** [comment]
> As I understand, Safari shows only a limited number of extension icons, and the order is not set in stone.

However, I cannot find the icon in `Customize Toolbar` window although the extension is enabled.

<img width="924" alt="Screen Shot 2022-08-16 at 19 16 01" src="https://user-images.githubusercontent.com/85087583/184856191-2b69c8f9-f014-433e-972d-774c31b894dd.png">

**Comment by xu-minghao317** [comment]
Confirmed this is a Safari issue, close question.
