### ISSUE TITLE
Errors in console on facebook.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardAssistant#389]
<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/207086707-150d6a70-aa75-4084-8b7d-6c9c146757a4.png)

</details>

AdGuard for Windows 7.12 n2

Domains: facebook.com,facebookcorewwi.onion

**Comment by ameshkov** [comment]
Are there any FB rules with scriptlets that override addEventListener?

**Comment by Alex-302** [comment]
Will check. I was going to disable the Assistant on this site(PR has not yet created).

**Comment by AdamWr** [comment]
It looks similar to this issue - https://github.com/AdguardTeam/Scriptlets/issues/266#issuecomment-1343984901

**Comment by Alex-302** [comment]
@ameshkov It is caused by `facebook.com#%#//scriptlet('prevent-addEventListener', 'scroll', 'showPopup')`
What should we do - leave as is(broken assistant and errors in console), or disable the legasi assistant on FB?

**Comment by ameshkov** [comment]
@Alex-302 wait for the scriptlet fix I think

**Comment by Alex-302** [comment]
Will check when fixed version will be available.

**Comment by Alex-302** [comment]
Not reproduced with 7.12 n9
