### ISSUE TITLE
There's a scrollbar on Tumblr website for `Block ads on this website` popup

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdguardAssistant#391]
### AdGuard Extension version

4.1.53

### Browser version

Firefox v109.0 - Chrome v109.0.5414.120

### OS version

Windows 10

### Issue Details

There are no user rules. Only this website has a scrollbar. Same for Chrome browser too.

### Expected Behavior

Shouldn't have a scroll bar for this website.

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/35523759/215114129-8eda6967-4934-4116-b030-571c0a76dd30.png)
</details>

**Comment by gork7777** [comment]
@mozartinio No, this is only for the `Tumblr` site.

**Comment by mozartinio** [comment]
@gork7777 
At the moment no one has a problem and there have been no similar requests
As soon as we can reproduce the problem -> we will immediately begin to solve it but in the meantime I will close the task
