### ISSUE TITLE
Unable to select the correct element on msn.com 

### ISSUE THREAD

**Issue by Numci** [AdguardTeam/AdguardAssistant#400]
### Issue URL (Ads)

[http://msn.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fmsn.com)

### Comment

Username: [@mshea77](https://github.com/mshea77)

> Ads remain regardless of how AdGuard is set - MSN ads appear when using ad block, or when turning it off for the site. Previously I was able to block elements from the old adguard link that was available in the sub-menu. when trying to block ads from the new adguard extension that appears in the address bar, there is no way to select the element to block, either from the rotating ads at the top of the page, or from the banner in the middle of the page. i have been dealing with this for over a month and i cannot get any assistance from you guys whatsoever.

<!DOCTYPE html><h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; caret-color: rgb(230, 237, 243); color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">System configuration</h3>

Information | value
-- | --
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.4
Browser: | Safari
DNS filtering: | server: adguard
Filters: | Ad Blocking:AdGuard Base,AdGuard Mobile AdsPrivacy:AdGuard Tracking Protection

Related issue: https://github.com/AdguardTeam/AdguardForiOS/issues/2065

**Comment by Eugene-Savenko** [comment]
Can we add more websites with non-functional assistant here, or it'd be better to file those as separate issues?

> After the last 4.4.6 update on iOS 16.4.1 the manual selection of the ads in Safari advanced protectionis not working because the buttons disappear once you select anything in the following page: https://eurekaddl.skin/newspapers/quotidiani-di-oggi-27-07-2023/

Helpdesk ID: 783664

**Comment by maximtop** [comment]
> Can we add more websites with non-functional assistant here, or it'd be better to file those as separate issues?
> 
> > After the last 4.4.6 update on iOS 16.4.1 the manual selection of the ads in Safari advanced protectionis not working because the buttons disappear once you select anything in the following page: https://eurekaddl.skin/newspapers/quotidiani-di-oggi-27-07-2023/
> 
> Helpdesk ID: 783664

Please create new issues. Usually, problems on each site are unique.
