### ISSUE TITLE
legacy assistant didn't appear on browsers. 

### ISSUE THREAD

**Issue by TommyKing** [AdguardTeam/AdguardAssistant#403]
palemoon browser 32.2.1
latest firefox
Adguard Desktop 7.13.2
Windows 11

the legacy assistant didnt appear. i know that firefox has a new assistant addon but that didnt help with palemoon. 
![does not have assistant](https://github.com/AdguardTeam/AdguardAssistant/assets/6888937/e260ad93-e1b5-4b25-8612-e968db5a221c)
![Screenshot 2023-07-03 225023](https://github.com/AdguardTeam/AdguardAssistant/assets/6888937/f7623b4a-e510-41d0-835a-fd1223d58ee4)

thanks

**Comment by TommyKing** [comment]
> @TommyKing Hello! Palemoon is not a primary browser, so we can't ensure AdGuard work in this browser. As for FireFox browser, it's better use our new Browser Assistant, because it isn't injected into websites like other userscripts are, and it can work on all websites, unlike the legacy Assistant which doesn't work on some webpages.

Then you should add not working in all browser in that legacy assistant. As of right now in nightly it said that it works on all browser

**Comment by Birbber** [comment]
We stopped supporting Legacy Assistant, but haven't removed it completely. Sorry if that info confused you.
I'm closing this issue for now. Please open a new one if needed.
