### ISSUE TITLE
Suggestion: Option to Auto-hide AdGuard Assistant after x seconds

### ISSUE THREAD

**Issue by SullieLore** [AdguardTeam/AdguardAssistant#404]
Not much more to the idea. I would like to use the userscript, but not always see the AdGuard icon at all times. I understand I can block the AdGuard icon from showing on certain websites, but I'd prefer to see it for a few seconds in case I am using a different browser. Thanks for reading.

**Comment by Birbber** [comment]
Hello! We no longer add new features to the legacy Assistant. 
It's better to use our new [Browser Assistant](https://github.com/AdguardTeam/BrowserAssistant), as it isn't injected into websites like userscripts, and it can work on all websites, unlike the legacy Assistant which doesn't work on some webpages.
