### ISSUE TITLE
Vivaldi/Vivaldi Snapshot is actually unable to use AdguardAssistant to block ads

### ISSUE THREAD

**Issue by QuantumRoseinAmethystVase** [AdguardTeam/AdguardAssistant#412]
Vivaldi/Vivaldi Snapshot is currently unable to use AdguardAssistant to block ads (at least the user filters).
Browser 1: Vivaldi 6.4.3160.44 (Stable channel) (arm64)
Browser 2: Vivaldi Snapshot 6.5.3201.4 (arm64)

<img width="320" alt="image" src="https://github.com/AdguardTeam/AdguardAssistant/assets/62452364/ae38b263-d106-4094-8d82-c71a94227b0b">

After installing the AdguardAssistant Browser Extension in the Chrome Store, the extension options look fine, with the ability to add user filters and connect with the local AdGuard. However, these user filters don't really work, i.e. the content that appears in the user filter will still appear on the web page.
These problems do not exist with Brave nightly 1.62.70 (arm64), which also has the chromium kernel.
Example pages: http://www.bilibili.com

<img width="1536" alt="image" src="https://github.com/AdguardTeam/AdguardAssistant/assets/62452364/83ea6a2b-a748-4364-ab98-de7a12e881ac">

User filters: bilibili.com##.desktop-download-tip

**Comment by alexx7311** [comment]
@QuantumRoseinAmethystVase Hello! We couldn't reproduce the problem. Please check if the problem reproducible in Vivaldi incognito mode or clear the browser cookies and refresh the page.

**Comment by alexx7311** [comment]
@QuantumRoseinAmethystVase Is the problem still relevant?
