### ISSUE TITLE
No Assistant icon on macaficionados.com

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardAssistant#44]
Both on Windows and Mac. Tested in Chrome.

Original post: https://forum.adguard.com/index.php?threads/21890/

**Comment by vozersky** [comment]
rep

**Comment by Bubu92** [comment]
Guys, just to let you know I found something strange. 

If we use Firefox and browse the websites:
`http://macaficionados.com
http://www.maxiapple.com
http://www.macworld.com`
We are not facing any concern. Adguard Assistant is present on the page.

So I guess it is more related to Safari with Adguard. Just my 2 cents! :)

**Comment by ameshkov** [comment]
The problem is with this script:
```
    var runAtDocumentEnd = function(eventListener) {
        if (document.readyState == "complete" || (document.readyState == "loaded" || document.readyState == "interactive")) {
            if (eventListener)
                eventListener.call(document)
        } else {
            var listenEvents = ["DOMContentLoaded", "load"];
            var eventListenerWrapper = function() {
                listenEvents.forEach(function(eventType) {
                    document.removeEventListener(eventType, eventListenerWrapper, false)
                });
                runAtDocumentEnd(eventListener)
            };
            listenEvents.forEach(function(eventType) {
                document.addEventListener(eventType, eventListenerWrapper, false)
            })
        }
    };
```

For some unknown reason, load events aren't fired. @4-life I need you to do a small research and find out what happens with the event.

**Comment by 4-life** [comment]
@ameshkov with which parameter the function **runAtDocumentEnd** is called?

**Comment by ameshkov** [comment]
One more example of this issue:
https://github.com/AdguardTeam/AdguardAssistant/issues/65

**Comment by 4-life** [comment]
Problem detected and solved. See: https://bugs.jquery.com/ticket/12282
