### ISSUE TITLE
Steam related website scripts broken due to new AG assistant

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/AdguardAssistant#45]
For example on steamcommunity i can't accept any friend requests anymore without "disabling adguard for 30 seconds".
Initially i thought it might be some browser addon like uMatrix blocking Valve's javascripts but the issue appeared in all AG filtered apps including the local steam client as shown below.

![https://i.imgur.com/EnyxnhG.png](https://i.imgur.com/EnyxnhG.png)
![https://i.imgur.com/SSvhhaA.gifv](https://i.imgur.com/SSvhhaA.gif)

[DebugLogs+FilteringLog+Steam_CEF_Log.zip](https://github.com/AdguardTeam/AdguardAssistant/files/1035467/Logs.zip) (PW: assist) If you need the database too just ping me :)

**Comment by ameshkov** [comment]
So if you disable Assistant the issues goes away, right?

**Comment by Bluscream** [comment]
Yes, if i click on ignore for 30 secs

**Comment by ameshkov** [comment]
> Yes, if i click on ignore for 30 secs

The thing is that it completely disables everything, not just the Assistant. As I recall, you have quite a lot of other extensions, could any of them be the culprit?

**Comment by Bluscream** [comment]
I'm 99% sure, just because i didn't install any new userscripts from the day the new assistant was introduced.

**Comment by ameshkov** [comment]
> I'm 99% sure, just because i didn't install any new userscripts from the day the new assistant was introduced.

It's quite easy to check -- disable Assistant and check it.

Along with Assistant there were some massive changes in the underlying extensions API and that might be the cause.

**Comment by Bluscream** [comment]
Assistant only? How?

**Comment by ameshkov** [comment]
Settings -> Extensions -> uncheck Adguard Assistant

**Comment by Bluscream** [comment]
Still broken :o but id didn't install new userscripts nor a big userscript update happened

https://i.imgur.com/ux30zvx.png

**Comment by ameshkov** [comment]
@Bluscream could you please narrow it down to the specific userscript which breaks it?

**Comment by Bluscream** [comment]
I have 122 Extensions, it might be a bit hard to narrow that down, should i still try?

**Comment by ameshkov** [comment]
> I have 122 Extensions, it might be a bit hard to narrow that down, should i still try?

Oh, man, that's just huge!

Does it help to disable "Extension" module completely?

**Comment by zebrum** [comment]
@Bluscream hi! Does the issue persist?

**Comment by Bluscream** [comment]
No. Can be closed, thanks :)
