### ISSUE TITLE
Assistant icon position should be relative to the bottom-right corner of a page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#47]
Steps to reproduce the issue:
1. Drag the icon somewhere on a page
2. Resize the browser window (make it smaller)

Expected behavior:
Assistant icon keeps visible (as it uses bottom-right corner as an anchor)

Actual behavior:
Assistant icon might become invisible

**Comment by 4-life** [comment]
Icon relative to the bottom-right corner of a page does not solve the problem because in this solution icon may pass outside left-top corner of a page. Solution is the adding window resize event listener

**Comment by 4-life** [comment]
#48
