### ISSUE TITLE
Prepare a dev build

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardAssistant#61]
The difference from the release build:

1. Add `Dev` postfix.
2. Publish to `gh-pages` through travis build.
3. Change downloadUrl and updateUrls accordingly.

Build output should consist of two files: `*.meta.js` and `*.user.js`

**Comment by 4-life** [comment]
Dev build is located at https://AdguardTeam.github.io/AdguardAssistant/assistant.user.js
