### ISSUE TITLE
[Feature request] Add support for extended css rules in the devtools

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/AdguardAssistant#64]
To debug extended css rules, currently one have to repeat adding several rules to user filter and refresh the page.

It would be helpful, if devtools provide ability to highlight elements matching a user-inputted selectors in ExtCss syntax, and provide ability to preview the page that the rule in action.

**Comment by ameshkov** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardBrowserExtension/issues/756
