### ISSUE TITLE
No Assistant icon on torrentleech.org

### ISSUE THREAD

**Issue by skipik** [AdguardTeam/AdguardAssistant#66]
I don't see assistant icon on [this link](https://www.torrentleech.org/torrents/browse).
It's a private torrent tracker and you have to be registered.

Windows 10 v1703 x64, Opera Developer 47, Adguard 6.2.369.1938.

**Comment by ameshkov** [comment]
Does HTTPS filtering work on that website in your case?

**Comment by ameshkov** [comment]
In my case beta considers this website's certificate invalid, hence does not filter it at all

**Comment by ameshkov** [comment]
Here is why:
https://github.com/AdguardTeam/AdguardForWindows/issues/1702

**Comment by skipik** [comment]
Yeah, you're right. It doesn't filter anything on that site. I'll wait for that #1702 to be fixed and check again.
