### ISSUE TITLE
Assistant icon misplaced after opening Assistant window

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardAssistant#68]
1. Open a site (e.g. http://store.steampowered.com/)

![image](https://user-images.githubusercontent.com/10995998/27490407-6c0758a0-583e-11e7-8ed8-4d90bd26c723.png)

2. Click on the assistan icon
3. Close the assistant
4. Open Chrome dev tools

![image](https://user-images.githubusercontent.com/10995998/27490439-8bb632ac-583e-11e7-94d8-1280f08a06b4.png)

5. Close dev tools
6. Assistant icon is misplaced

![image](https://user-images.githubusercontent.com/10995998/27490468-a3dd87e0-583e-11e7-86f1-0789f6e20a02.png)

**Comment by ameshkov** [comment]
Should be resolved by this:
https://github.com/AdguardTeam/AdguardAssistant/pull/74
