### ISSUE TITLE
[Feature Request] Add a possibility to completely whitelist website

### ISSUE THREAD

**Issue by linaspasv** [AdguardTeam/AdguardAssistant#71]
I have experienced some of the problems on multiple webpages where I couldn't whitelist them out of the box just by clicking "Add Exception". 

My investigation showed that these particular websites use ``$generichide`` modifiers (e.g. http://play.tv3.lt/ with EasyList Lithuania filter). 
My suggestion would be to add ``$important`` modifier out of the box when auto-generating rule from the extension.

For more reference - https://github.com/AdguardTeam/AdguardFilters/issues/5456

**Comment by ameshkov** [comment]
> My suggestion would be to add $important modifier out of the box when auto-generating rule from the extension.

Makes sense indeed, thank you!
