### ISSUE TITLE
Assistant icon dragging issues

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardAssistant#72]
Assistant icon can be dragged behind scroll bar.

Page with default settings (the assistant automatically detects the scroll bar and changes the icon position accordingly):

Without scroll bar:

![image](https://user-images.githubusercontent.com/10995998/27492129-58a12ece-5845-11e7-8779-1308eccbb633.png)

With scroll bar:

![image](https://user-images.githubusercontent.com/10995998/27492143-66e279de-5845-11e7-9c35-8f745755f247.png)

Assistant manually dragged behind scroll bar:

![image](https://user-images.githubusercontent.com/10995998/27492186-8ef13ab4-5845-11e7-91c8-4aebb7beff60.png)

_______________________________________

Also:

Contact with the edges while dragging the Assistant icon stops the ability to drag it. The icon has to be clicked again to continue dragging the icon elsewhere. Not sure if that can and should be fixed, but it can get quite annoying though ;)

**Comment by 4-life** [comment]
scroll bar problem solved https://github.com/AdguardTeam/AdguardAssistant/issues/74
Contact with the edges while dragging the Assistant icon stops the ability to drag it - its not a bug
