### ISSUE TITLE
watchfree.to - no assistant

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardAssistant#73]
Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/5477

**Comment by 4-life** [comment]
Problem detected and solved. See: https://bugs.jquery.com/ticket/12282

**Comment by ypetruk** [comment]
still no Assistant at this website

MacOS, Chrome, all filters are updated

![screen shot 2017-06-30 at 6 48 08 pm](https://user-images.githubusercontent.com/28784344/27743454-b9915e5a-5dc4-11e7-8143-795b17a15b5b.png)

**Comment by vozersky** [comment]
@ypetruk   
![image](https://user-images.githubusercontent.com/17472907/27745383-d0a0bd32-5dcb-11e7-92f2-fd826a7f79d6.png)

**Comment by ypetruk** [comment]
got it, sorry

**Comment by ameshkov** [comment]
@ypetruk AG for Mac is not yet ready for the new Assistant version, will get it eventually.
