### ISSUE TITLE
Assistant icon won't appear until page is reloaded

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardAssistant#80]
Not sure if that's an issue with the Assistant or caused by something different.

On mobile clicking on Google AMP links won't show the Assistant icon on that page. After reloading the page the icon will appear.

1. Search for something like "Berlin" and click on any AMP link:

![image](https://user-images.githubusercontent.com/10995998/27762088-906b460c-5e6a-11e7-8327-939b108f73c3.png)

2. No Assistant icon will show up on that page:

![image](https://user-images.githubusercontent.com/10995998/27762091-b57b3cc2-5e6a-11e7-8c12-8fe21ab00fa2.png)

3. Reload the page and the icon will appear:

![image](https://user-images.githubusercontent.com/10995998/27762099-dad71db0-5e6a-11e7-8ef0-33f7d77860f2.png)

Using Assistant 4.0.7

**Comment by ameshkov** [comment]
It seems that AMP pages are loaded differently.

What mobile device do you use?

**Comment by danidoedel** [comment]
Discovered that using Windows 10 with Chrome and iPhone as device settings.

**Comment by ameshkov** [comment]
@danidoedel got it, thank you! Assigned to 4.2 (mobile layout support)
