### ISSUE TITLE
Assistant's menu should disappear when you click everywhere on site space

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardAssistant#86]
Adguard assistant dev 4.0.9

STR:

1. Open any webpage

2. Click on assistant 

3. Click on some rectangle space around assistant menu. Approximate location of this space highlighted in red:
<details>

![screenshot at jul 10 14-33-43](https://user-images.githubusercontent.com/23637588/28018518-44d4d6cc-6586-11e7-8b7e-bedb04ac1be7.png)

</details>

Expected result:
Assistant menu goes away.

Actual result:
Menu is still there.

**Comment by ameshkov** [comment]
@zebrum Unfortunately, this is by design, there always will be a space around Assistant which cannot be clicked through.
