### ISSUE TITLE
Dragging icon out of the viewport opens settings window

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardAssistant#92]
Dragging the assistant icon out of the viewport opens the settings window. I'm not sure, but I don't think it is intended as it does only happen every two times or something like that and I don't see any benefit, it's just annoying.
Hope you can reproduce that issue.

**Comment by vozersky** [comment]
@danidoedel 
https://screencast.com/t/eXtEQiyBmq
You mean like this, right?

**Comment by danidoedel** [comment]
Yep exactly

**Comment by vozersky** [comment]
This is related to fixes made for touchscreens.
I wouldn't call it an annoying bug but we have to think about fixing it.
