### ISSUE TITLE
Able to move settings window completely out of viewport

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardAssistant#94]
Settings window can completely moved outside of the viewport (below the taskbar). I think it can be useful to move the window out of your view (although you could just close it), but not completely. Maybe just until the mouse cursor reaches the edge of the window?

![image](https://user-images.githubusercontent.com/10995998/28166432-244a6968-67d8-11e7-839e-a41b777e4805.png)

**Comment by vozersky** [comment]
it can be moved only to the right side and below, 
we should rather remove the limitation for moving the window up\left or add the limitation for all sides, anyway we should unify this behavior
