### ISSUE TITLE
Invisible settings window after reloading frame

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardAssistant#95]
Right click on the settings window and reloading the frame makes the settings window invisible, nothing below the invisible settings window can be clicked:

![image](https://user-images.githubusercontent.com/10995998/28166850-d580d14e-67d9-11e7-9f89-cc8145da473f.png)

![image](https://user-images.githubusercontent.com/10995998/28166938-1bfc3de8-67da-11e7-94d7-1030d37e8bb7.png)

**Comment by vozersky** [comment]
are you sure? it does disappear, true, but you are able to click through it

**Comment by danidoedel** [comment]
No, I'm not able to click through it.

**Comment by danidoedel** [comment]
![adguard](https://user-images.githubusercontent.com/10995998/28169311-3954ca56-67e2-11e7-93bb-af73a0e32b96.gif)

**Comment by 4-life** [comment]
reproduced

**Comment by ameshkov** [comment]
@4-life the easiest solution would be to prohibit right-click inside of the iframe
