### ISSUE TITLE
Assistant icon while printing website

### ISSUE THREAD

**Issue by danidoedel** [AdguardTeam/AdguardAssistant#96]
Is it possible to not print the assistant icon? Or at least print it at the actual position on the site ;)

![image](https://user-images.githubusercontent.com/10995998/28167386-c8d7ca40-67db-11e7-8b0d-1c311f7a0238.png)

![image](https://user-images.githubusercontent.com/10995998/28167449-f63f43aa-67db-11e7-8eea-27b2e31988e1.png)

**Comment by vozersky** [comment]
not sure about this one, @4-life pls assist

**Comment by 4-life** [comment]
We can hide the icon when printing

**Comment by vozersky** [comment]
@danidoedel thanks a lot for your reports, we really appreciate it!

**Comment by danidoedel** [comment]
@vozersky You are welcome! I'm glad I can help to improve your product this way :)
