### ISSUE TITLE
Assistant always opens the English version of reports.adguard.com site

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardAssistant#98]
When the app uses Russian and you want to read the report, it always opens the English version.

1. Make sure Adguard is set to use Russian,
2. Go to a site, click on the Assistant logo
3. Click Откріть отчет безопасности
4. It opens https://reports.adguard.com/eng/..../report.html

Reproduced on Windows 10 with English localization, Adguard 6.1.331.1732 (Russian), Assistant 3.0.116

**Comment by ameshkov** [comment]
@4-life just check that the report URL does not contain any language, it should be website who decides which language should be used.

**Comment by 4-life** [comment]
@ameshkov URL not contain any language so this is on website
